import React from 'react';
import { m } from 'framer-motion';
import agencies from '../data/agencies.json';
import { QUESTIONS } from '../data/quizQuestions.js';
import opportunitiesMeta from '../data/opportunitiesMeta.json';
import usePrefersReducedMotion from '../hooks/usePrefersReducedMotion.js';
import SpotlightOverlay from './SpotlightOverlay.jsx';

// Counts come from the same files the quiz itself reads (src/data/
// agencies.json, src/data/quizQuestions.js) rather than being hand-typed —
// the audit flagged this exact line as a stale claim ("opportunity count
// went 55 → 1,440 without the copy noticing"): it said "14" when
// agencies.json already had 28 real entries. The opportunities count reuses
// src/data/opportunitiesMeta.json — already generated by
// scripts/generate-component.js (the same pipeline OpportunitiesExplorer.jsx
// itself comes from) — rather than a second script computing the same
// number a different way.
//
// Deliberately not "A live map, not a static graphic" / "A matcher that
// shows its work" / "An explorer stocked with real openings" — three
// parallel "A/An ___" titles in a 3-up icon grid is close to a verbatim
// match for the generic AI feature-section template (see the design-audit
// artifact this replaces). Each line below is shaped differently on
// purpose — a fragment, a number-led clause, an imperative — so they don't
// scan as one templated triplet, and there's no icon-in-a-circle per item
// (that motif alone reads as decoration reached for by default rather than
// a considered mark).
const ITEMS = [
  {
    kicker: 'Map',
    line: 'Refreshes weekly, straight from Joshua Project.'
  },
  {
    kicker: 'Quiz',
    line: () => `${QUESTIONS.length} questions, ${agencies.length} agencies, and a real answer for why each one matched — or didn't.`
  },
  {
    kicker: 'Listings',
    line: () =>
      `${opportunitiesMeta.opportunityCount.toLocaleString()} openings across ${opportunitiesMeta.agencyCount} agencies. Filter by role, region, or term length and skip the scrolling.`
  }
];

const EASE = [0.16, 1, 0.3, 1];

// A single stacked column, ragged-right, not a grid of equal-width cells —
// three unrelated facts read down the page like a spec sheet rather than
// three interchangeable slots in a template.
function CapabilityItem({ item, index }) {
  const prefersReduced = usePrefersReducedMotion();
  return (
    <m.div
      className="capability-item"
      data-reveal
      // initial={false} under reduced motion — see RevealOnScroll.jsx for
      // why this beats an opacity:0 that depends on whileInView firing.
      initial={prefersReduced ? false : { opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.4 }}
      transition={{ duration: 0.55, delay: index * 0.07, ease: EASE }}
    >
      <span className="capability-kicker">{item.kicker}</span>
      <p>{typeof item.line === 'function' ? item.line() : item.line}</p>
    </m.div>
  );
}

export default function Capabilities() {
  const prefersReduced = usePrefersReducedMotion();
  return (
    <section className="capabilities">
      <SpotlightOverlay />
      <m.h2
        data-reveal
        initial={prefersReduced ? false : { opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.5 }}
        transition={{ duration: 0.6, ease: EASE }}
      >
        What&rsquo;s actually in here
      </m.h2>
      <div className="capabilities-list">
        {ITEMS.map((item, i) => (
          <CapabilityItem key={item.kicker} item={item} index={i} />
        ))}
      </div>
    </section>
  );
}
