import React from 'react';
import { m } from 'framer-motion';
import { Globe, Compass, Briefcase } from '@phosphor-icons/react';
import agencies from '../data/agencies.json';
import { QUESTIONS } from '../data/quizQuestions.js';
import opportunitiesMeta from '../data/opportunitiesMeta.json';
import useTilt from '../hooks/useTilt.js';
import usePrefersReducedMotion from '../hooks/usePrefersReducedMotion.js';
import SpotlightOverlay from './SpotlightOverlay.jsx';

// Counts come from the same files the quiz itself reads (src/data/
// agencies.json, src/data/quizQuestions.js) rather than being hand-typed —
// the audit flagged this exact line as a stale claim ("opportunity count
// went 55 → 1,440 without the copy noticing"): it said "14" when
// agencies.json already had 28 real entries. The opportunities count reuses
// src/data/opportunitiesMeta.json — already generated by
// scripts/generate-component.js (the same pipeline OpportunitiesExplorer.jsx
// itself comes from) — rather than a second script computing the same
// number a different way.
const ITEMS = [
  {
    icon: Globe,
    title: 'A live map, not a static graphic',
    desc: 'The world map pulls real, current people-group data from Joshua Project — not a one-time snapshot.'
  },
  {
    icon: Compass,
    title: 'A matcher that shows its work',
    desc: `${QUESTIONS.length} questions, ${agencies.length} researched sending agencies, and a results view that explains exactly what matched and what to ask about — not just a ranked list.`
  },
  {
    icon: Briefcase,
    title: 'An explorer stocked with real openings',
    desc: `${opportunitiesMeta.opportunityCount.toLocaleString()} live opportunities across ${opportunitiesMeta.agencyCount} agencies — filter by role, region, or term length instead of scrolling one long list.`
  }
  // A 4th item ("A checklist that adapts to you", CheckSquare icon) is
  // temporarily removed — see TopNav.jsx's own comment: the checklist
  // page/route is still live, just pulled from the nav tabs for now, so
  // promoting it here would point somewhere the primary nav no longer
  // surfaces. Re-add (and re-import CheckSquare above) once the nav link
  // comes back.
];

const EASE = [0.16, 1, 0.3, 1];

// A 2x2 grid, not a single narrow column: four parallel things (not a
// sequence, so no numbering — see CLAUDE.md-adjacent guidance against
// numbering content that isn't actually ordered) filling the same width as
// the heading above instead of a left-hung column leaving the right half
// of the section empty. The icon sits inline with its title, not in its
// own left-hand column — one compact visual mark per item, not a repeated
// "icon | text" layout down the page.
function CapabilityItem({ item, index }) {
  const tilt = useTilt();
  const prefersReduced = usePrefersReducedMotion();
  return (
    <m.div
      className="capability-item"
      data-reveal
      // initial={false} under reduced motion — see RevealOnScroll.jsx for
      // why this beats an opacity:0 that depends on whileInView firing.
      initial={prefersReduced ? false : { opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.4 }}
      transition={{ duration: 0.55, delay: index * 0.07, ease: EASE }}
    >
      <h3>
        <m.span ref={tilt.ref} style={tilt.style} className="capability-glyph">
          <item.icon size={16} weight="bold" />
        </m.span>
        {item.title}
      </h3>
      <p>{item.desc}</p>
    </m.div>
  );
}

export default function Capabilities() {
  const prefersReduced = usePrefersReducedMotion();
  return (
    <section className="capabilities">
      <SpotlightOverlay />
      <m.h2
        data-reveal
        initial={prefersReduced ? false : { opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.5 }}
        transition={{ duration: 0.6, ease: EASE }}
      >
        What&rsquo;s actually in here
      </m.h2>
      <div className={`capabilities-grid${ITEMS.length === 3 ? ' capabilities-grid--three' : ''}`}>
        {ITEMS.map((item, i) => (
          <CapabilityItem key={item.title} item={item} index={i} />
        ))}
      </div>
    </section>
  );
}
