// AUTO-GENERATED by scripts/generate-component.js — do not edit by hand.
// Re-run: npm run generate-component
//
// Design tokens applied (from src/styles/tokens.css):
//   --ink-navy: #16233b
//   --atlas-paper: #faf7f0
//   --voyage-teal: #2b6e76
//   --status-unreached: #b5482f
//   --status-formative: #d9a441
//   --status-reached: #4c8a5e
//   --line: rgba(22, 35, 59, 0.15)
//   --muted-text: rgba(22, 35, 59, 0.65)
//   --font-display: 'Fraunces Variable', Georgia, serif
//   --font-body: 'Inter Variable', system-ui, sans-serif
//   --font-mono: 'IBM Plex Mono', 'SFMono-Regular', monospace
//   --space-1: 4px
//   --space-2: 8px
//   --space-3: 12px
//   --space-4: 16px
//   --space-6: 24px
//   --space-8: 32px
//   --space-12: 48px
//   --space-16: 64px
//   --radius: 8px
//   --shadow: 0 2px 12px rgba(22, 35, 59, 0.12)
//   --focus-ring: 0 0 0 2px var(--atlas-paper), 0 0 0 4px var(--voyage-teal)
//
// Generated: "2026-07-10T19:28:26.744Z"
// Opportunities: 55 across 7 agencies

import React, { useState, useEffect, useMemo } from 'react';
import { MagnifyingGlass, Funnel, Heart, EnvelopeSimple, MapPin, Briefcase, Clock, X, CaretDown } from '@phosphor-icons/react';
import { supabase } from '../supabaseClient.js';
import RevealOnScroll from './RevealOnScroll.jsx';

const BAKED_OPPORTUNITIES = [
  {
    "id": "6df756e5-fc41-4f54-8073-8bbc141d5c94",
    "agency": "Africa Inland Mission (AIM)",
    "title": "Inbound",
    "url": "https://us.aimint.org/serve/#inbound",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "Inbound is a one-year on-boarding program designed to help new missionaries land well and become equipped to faithfully serve in long-term ministry. Inbound is often the first step to serving on a church planting team."
  },
  {
    "id": "e0dfbb49-2840-492e-acb2-2ff230c2c433",
    "agency": "Africa Inland Mission (AIM)",
    "title": "Our vision is to see Christ-centered churches established and thriving among all of Africa’s peoples. Whether you are new to missions, or come with unique skills and experience, there’s a place for you.",
    "url": "https://us.aimint.org/serve/explore-serving/",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "Ask questions. Talk with a Mission Mobilizer. Start an application."
  },
  {
    "id": "6e9a5811-8abb-4bcc-9a91-04d989b13f21",
    "agency": "Africa Inland Mission (AIM)",
    "title": "The 'GO' Program",
    "url": "https://us.aimint.org/serve/#the-go-program",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "For short-term workers, the Go Program is a two-month discipleship and mission training program that seeks to develop Christlike character and instill basic skills for outreach among unreached people groups."
  },
  {
    "id": "f76c1537-1105-414f-9d73-68821aa97218",
    "agency": "Ethnos360",
    "title": "Career",
    "url": "https://ethnos360.org/go/career-missions",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "career/long-term",
    "description": null
  },
  {
    "id": "b14a5632-2235-4650-babc-09db8db4f7ee",
    "agency": "Ethnos360",
    "title": "WAYUMI",
    "url": "https://ethnos360.org/short-term-trips/wayumi",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  },
  {
    "id": "878bdffd-64c1-4a56-8c9b-39f815526342",
    "agency": "International Mission Board (IMB)",
    "title": "Browse Ways To Get Involved",
    "url": "https://www.imb.org/pray/",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "Pray for global missions and join efforts that advance the gospel, creating lasting impact."
  },
  {
    "id": "6e3cbc01-365f-48c4-b3c4-e3ae93477339",
    "agency": "International Mission Board (IMB)",
    "title": "Filters",
    "url": "https://www.imb.org/get-involved",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "Discover where God may be calling you to serve around the world."
  },
  {
    "id": "bcb59916-38d0-4513-8c25-01823854f160",
    "agency": "International Mission Board (IMB)",
    "title": "Find a Mission Trip",
    "url": "https://www.imb.org/opportunity-finder/",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  },
  {
    "id": "ce060489-6147-4f4e-a167-113fe2570216",
    "agency": "OMF International",
    "title": "Serve in Australia",
    "url": "https://opportunities.omf.org/Locations/#australia",
    "location": "Australia",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "9ecb5f71-c221-4d64-9e33-e09a4aaa4792",
    "agency": "OMF International",
    "title": "Serve in Belgium",
    "url": "https://opportunities.omf.org/Locations/#belgium",
    "location": "Belgium",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "398160da-546a-479f-b479-03cf8f3a9d9a",
    "agency": "OMF International",
    "title": "Serve in Bhutan",
    "url": "https://opportunities.omf.org/Locations/#bhutan",
    "location": "Bhutan",
    "region": "South Asia",
    "role_type": null,
    "term_length": null,
    "description": "Join what God is doing in the only Tibetan Buddhist kingdom in the world. LEARN MORE Opportunities"
  },
  {
    "id": "f90d8c6a-6db2-4379-98ca-bc5f5c8f1faa",
    "agency": "OMF International",
    "title": "Serve in Brunei Darussalam",
    "url": "https://opportunities.omf.org/Locations/#brunei-darussalam",
    "location": "Brunei Darussalam",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "bd19e416-fee9-466f-b847-995877cf6c07",
    "agency": "OMF International",
    "title": "Serve in Cambodia",
    "url": "https://opportunities.omf.org/Locations/#cambodia",
    "location": "Cambodia",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "Cambodia is looking for pioneers and partners to open new avenues for the Gospel, build up the local church, and disciple believers in the workplace. LEARN MORE Opportunities"
  },
  {
    "id": "de21cb3c-72cf-4234-9e60-6aadfdb71631",
    "agency": "OMF International",
    "title": "Serve in Canada",
    "url": "https://opportunities.omf.org/Locations/#canada",
    "location": "Canada",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "1ab0c179-a0ee-473d-8756-ab9de1ffdf47",
    "agency": "OMF International",
    "title": "Serve in China",
    "url": "https://opportunities.omf.org/Locations/#china",
    "location": "China",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "The church in China is responding by developing its role in society, its response to pressure, its strategy in growth, and its heart in sending out cross-cultural workers. LEARN MORE Opportunities"
  },
  {
    "id": "26dba6c8-3605-4821-94a8-e851ea9fba41",
    "agency": "OMF International",
    "title": "Serve in East Timor",
    "url": "https://opportunities.omf.org/Locations/#east-timor",
    "location": "East Timor",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "d51eda75-eab5-4f8a-83d1-a6b828312a78",
    "agency": "OMF International",
    "title": "Serve in Germany",
    "url": "https://opportunities.omf.org/Locations/#germany",
    "location": "Germany",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "5dafbaa2-6349-4cf9-b1e4-2405d8496ddd",
    "agency": "OMF International",
    "title": "Serve in Hong Kong",
    "url": "https://opportunities.omf.org/Locations/#hong-kong",
    "location": "Hong Kong",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "59e1a50a-62a0-4908-9eeb-c446e66ea88e",
    "agency": "OMF International",
    "title": "Serve in Indonesia",
    "url": "https://opportunities.omf.org/Locations/#indonesia",
    "location": "Indonesia",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "1514a378-866a-44f6-b9a7-68b64ed1d983",
    "agency": "OMF International",
    "title": "Serve in Japan",
    "url": "https://opportunities.omf.org/Locations/#japan",
    "location": "Japan",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "Japan needs workers to partner with the Japanese church in the task of sharing the gospel and making disciples. LEARN MORE Opportunities"
  },
  {
    "id": "2e13aab7-7d36-4fc8-80ff-2df9922bb012",
    "agency": "OMF International",
    "title": "Serve in Laos",
    "url": "https://opportunities.omf.org/Locations/#laos",
    "location": "Laos",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "The church in Laos is under constant pressure as the communist government actively promotes Buddhism. LEARN MORE Opportunities"
  },
  {
    "id": "cc23fbbe-ce40-470f-831c-8ce4c2abc001",
    "agency": "OMF International",
    "title": "Serve in Malaysia",
    "url": "https://opportunities.omf.org/Locations/#malaysia",
    "location": "Malaysia",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "This country needs people with creativity to reach out to non-believers, and people with a calling for discipleship training to strengthen and encourage believers. LEARN MORE Opportunities"
  },
  {
    "id": "54d5bbc4-11c7-4318-a5ef-f76a3a288060",
    "agency": "OMF International",
    "title": "Serve in Mongolia",
    "url": "https://opportunities.omf.org/Locations/#mongolia",
    "location": "Mongolia",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "In 1990, there were less than 10 known Christians in Mongolia. Today there are more than 40,000 believers meeting in more than 400 churches. LEARN MORE Opportunities"
  },
  {
    "id": "b1ef3e3b-ecd2-413a-be0e-21d2d950dc4c",
    "agency": "OMF International",
    "title": "Serve in Myanmar",
    "url": "https://opportunities.omf.org/Locations/#myanmar",
    "location": "Myanmar",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "Myanmar considers itself one of the last outposts of true Buddhism. LEARN MORE Opportunities"
  },
  {
    "id": "4d4fb474-d547-457b-a793-0195381c4baa",
    "agency": "OMF International",
    "title": "Serve in Nepal",
    "url": "https://opportunities.omf.org/Locations/#nepal",
    "location": "Nepal",
    "region": "South Asia",
    "role_type": null,
    "term_length": null,
    "description": "There are new opportunities opening up in Nepal. Join us as we visit ministries, pray on site and experience God at work. LEARN MORE Opportunities"
  },
  {
    "id": "098619b8-bc8d-40b1-b495-aab4c748bb84",
    "agency": "OMF International",
    "title": "Serve in Netherlands",
    "url": "https://opportunities.omf.org/Locations/#netherlands",
    "location": "Netherlands",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "b58f3f18-2124-467f-a76a-9212585e05f8",
    "agency": "OMF International",
    "title": "Serve in New Zealand",
    "url": "https://opportunities.omf.org/Locations/#new-zealand",
    "location": "New Zealand",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "4b4dc297-1dbf-42fb-a718-524259925e5d",
    "agency": "OMF International",
    "title": "Serve in North Korea",
    "url": "https://opportunities.omf.org/Locations/#north-korea",
    "location": "North Korea",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "The Democratic People’s Republic of North Korea [DPRK] is probably the most closed country in the world. LEARN MORE Opportunities"
  },
  {
    "id": "6a2267e8-b9a9-4cb4-87bb-63d889997df6",
    "agency": "OMF International",
    "title": "Serve in Philippines",
    "url": "https://opportunities.omf.org/Locations/#philippines",
    "location": "Philippines",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "There is still a need to bring the Gospel in all its fullness to this diverse nation that is open to missionaries. LEARN MORE Opportunities"
  },
  {
    "id": "3469938a-c464-4738-9712-9440da57350c",
    "agency": "OMF International",
    "title": "Serve in Singapore",
    "url": "https://opportunities.omf.org/Locations/#singapore",
    "location": "Singapore",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "OMF in Singapore has two major thrusts: OMF Singapore continues to partner with churches in cross-cultural missions and in the formal training of pastors, missionaries and disciple-makers; OMF's global base for serving the Fellowship in pursuing its vision and mission is our International Center, located in Singapore since the early 1950s. LEARN MORE Opportunities"
  },
  {
    "id": "07e2c439-7684-4ea4-b898-ec5c99bd0498",
    "agency": "OMF International",
    "title": "Serve in South Africa",
    "url": "https://opportunities.omf.org/Locations/#south-africa",
    "location": "South Africa",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "be242226-bee0-4790-9621-4a44424a6fb3",
    "agency": "OMF International",
    "title": "Serve in South Korea",
    "url": "https://opportunities.omf.org/Locations/#south-korea",
    "location": "South Korea",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "52533880-0915-44ba-afc0-a7361112c3e1",
    "agency": "OMF International",
    "title": "Serve in Switzerland",
    "url": "https://opportunities.omf.org/Locations/#switzerland",
    "location": "Switzerland",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "0d0ff5ec-0ca1-4e27-b449-214152ce770c",
    "agency": "OMF International",
    "title": "Serve in Taiwan",
    "url": "https://opportunities.omf.org/Locations/#taiwan",
    "location": "Taiwan",
    "region": "East Asia",
    "role_type": null,
    "term_length": null,
    "description": "Taiwan is a wealthy country and is wide open to Christian activities and to missionary work. LEARN MORE Opportunities"
  },
  {
    "id": "c2e09eb5-b6f0-4910-9b5d-ecb3d927c028",
    "agency": "OMF International",
    "title": "Serve in Thailand",
    "url": "https://opportunities.omf.org/Locations/#thailand",
    "location": "Thailand",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "Less than one percent of the 65 million people in Thailand follow Jesus despite over 170 years of evangelism. LEARN MORE Opportunities"
  },
  {
    "id": "6b9970d3-44f6-4f89-9096-ac2f5e1ea377",
    "agency": "OMF International",
    "title": "Serve in United Kingdom",
    "url": "https://opportunities.omf.org/Locations/#united-kingdom",
    "location": "United Kingdom",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "01d75f14-cf01-4e37-9b3a-db0b2a46fbb4",
    "agency": "OMF International",
    "title": "Serve in USA",
    "url": "https://opportunities.omf.org/Locations/#usa",
    "location": "USA",
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "If God has given you a heart for the peoples of East Asia, you can be part of God's purposes for them in different practical ways, even in your home country. LEARN MORE Opportunities"
  },
  {
    "id": "5dc7374a-b623-4748-9ff9-606ff35e60ac",
    "agency": "OMF International",
    "title": "Serve in Vietnam",
    "url": "https://opportunities.omf.org/Locations/#vietnam",
    "location": "Vietnam",
    "region": "Southeast Asia",
    "role_type": null,
    "term_length": null,
    "description": "Vietnam's peoples represent one of our most neglected major frontiers. LEARN MORE Opportunities"
  },
  {
    "id": "0e7210ac-2354-4bd5-94d1-38497d48a3c2",
    "agency": "Pioneers",
    "title": "Edge",
    "url": "https://pioneers.org/go/edge-trips",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "short-term (under 2 years)",
    "description": "Ready for an opportunity that could change your life forever? Trips of 8-12 weeks can take you to the ends of the earth to work with Pioneers teams and share the name of Jesus.Applications for summer 2026 trips are now closed. Check back in September for 2027 trips."
  },
  {
    "id": "b9ce444f-028a-4a89-80a2-3fc96829a6de",
    "agency": "Pioneers",
    "title": "Hear From Past Edgers",
    "url": "https://pioneers.org/search?opp-type=Edge",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "short-term (under 2 years)",
    "description": "– Edger from a Southeast Asia team"
  },
  {
    "id": "d1a5352d-64f7-428b-875b-c32fee2a5ab0",
    "agency": "Pioneers",
    "title": "Opportunities",
    "url": "https://pioneers.org/#",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "short-term (under 2 years)",
    "description": "Our Edge program empowers college-aged adults to explore God’s mission to the unreached through 8 to 12 week summer mission trips. Serve alongside field workers, immerse in new cultures, and deepen your understanding of God’s calling. Whether you’re drawn to a specific opportunity or have something else in mind, we’re ready to help you make an impact. Let’s talk!"
  },
  {
    "id": "1d263895-aa81-4455-a25d-40ae7b1a3752",
    "agency": "Pioneers",
    "title": "Pioneers — Encore (50+)",
    "url": "https://pioneers.org/go/encore",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "career/long-term",
    "description": "Explore Encore (50+) opportunities with Pioneers."
  },
  {
    "id": "53f5f20c-ff4b-40b6-a3ac-cb0f9cab2b04",
    "agency": "Pioneers",
    "title": "Pioneers — Internships",
    "url": "https://pioneers.org/go/internships",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "short-term (under 2 years)",
    "description": "Explore Internships opportunities with Pioneers."
  },
  {
    "id": "f8b8baea-7359-43d6-bacd-d5030abb8311",
    "agency": "Pioneers",
    "title": "Pioneers — Long-Term",
    "url": "https://pioneers.org/go/long-term",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "career/long-term",
    "description": "Explore Long-Term opportunities with Pioneers."
  },
  {
    "id": "0712d527-bd04-4d19-9dc5-bf7a2d36356b",
    "agency": "Pioneers",
    "title": "Pioneers — Switchboard (creative access)",
    "url": "https://pioneers.org/go/switchboard",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "career/long-term",
    "description": "Explore Switchboard (creative access) opportunities with Pioneers."
  },
  {
    "id": "4d31c3c9-cfbd-4e2c-8f4d-d15b13f382ac",
    "agency": "Pioneers",
    "title": "Pioneers — Venture (short-term teams)",
    "url": "https://pioneers.org/go/venture",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "short-term (under 2 years)",
    "description": "Explore Venture (short-term teams) opportunities with Pioneers."
  },
  {
    "id": "fa6572e3-0cb1-4f3a-b3ef-102ecb201038",
    "agency": "World Team",
    "title": "Opportunities",
    "url": "https://us.worldteam.org/opportunities/addiction-recovery-counselor-cameroon/",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": "World Team currently has hundreds of missions opportunities for you to bring the hope of the gospel to the unreached."
  },
  {
    "id": "467a774a-7991-4dbd-a3cd-37f1b3f6f06b",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Discipleship Training School",
    "url": "https://ywam.org/explore",
    "location": null,
    "region": null,
    "role_type": "education/TESOL",
    "term_length": "short-term (under 2 years)",
    "description": null
  },
  {
    "id": "549b45c6-3028-429f-9f28-e6fecda066f1",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Families, Children and Teens",
    "url": "https://ywam.org/about-us/for-children-and-teens",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  },
  {
    "id": "bb851d8d-96ba-4780-9e0e-93e6f42110a1",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Join",
    "url": "https://ywam.org/get-involved-now",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  },
  {
    "id": "4c40086c-478f-4321-87c8-e374f060c29b",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Join Staff",
    "url": "https://ywam.org/get-involved-now/join-staff",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "career/long-term",
    "description": null
  },
  {
    "id": "5f051d0e-7939-49fd-a8c9-e60caccb1ad9",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Our Ministries",
    "url": "https://ywam.org/about-us/ministries",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  },
  {
    "id": "01e4757d-53b5-4e48-bd0e-d80563d9cfbc",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Outreach Trips",
    "url": "https://ywam.org/get-involved-now/outreach-trips",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": "short-term (under 2 years)",
    "description": null
  },
  {
    "id": "e78348c2-1eaf-4fb4-abd5-bb485ff2d503",
    "agency": "Youth With A Mission (YWAM)",
    "title": "University of the Nations Courses",
    "url": "https://ywam.org/training/university-of-the-nations",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  },
  {
    "id": "705aadbe-d950-4547-ba58-3605eef4c2f0",
    "agency": "Youth With A Mission (YWAM)",
    "title": "Volunteer",
    "url": "https://ywam.org/get-involved-now/volunteer",
    "location": null,
    "region": null,
    "role_type": null,
    "term_length": null,
    "description": null
  }
];

const REGIONS = [
  "East Asia",
  "South Asia",
  "Southeast Asia"
];
const ROLE_TYPES = [
  "education/TESOL"
];
const TERM_LENGTHS = [
  "short-term (under 2 years)",
  "career/long-term"
];

function FilterChip({ label, active, onClick }) {
  return (
    <button
      type="button"
      className={`opp-filter-chip${active ? ' opp-filter-chip--active' : ''}`}
      onClick={onClick}
    >
      {label}
    </button>
  );
}

function OpportunityCard({ opp, saved, onToggleSave, onInquire }) {
  return (
    <RevealOnScroll className="opp-card-wrapper">
      <article className="opp-card">
        <div className="opp-card-header">
          <span className="opp-card-agency">{opp.agency}</span>
          <div className="opp-card-actions">
            <button
              type="button"
              className={`opp-icon-btn${saved ? ' opp-icon-btn--saved' : ''}`}
              onClick={() => onToggleSave(opp.id)}
              aria-label={saved ? 'Remove from saved' : 'Save opportunity'}
            >
              <Heart weight={saved ? 'fill' : 'regular'} size={18} />
            </button>
          </div>
        </div>

        <h3 className="opp-card-title">{opp.title}</h3>

        {opp.description && (
          <p className="opp-card-desc">{opp.description}</p>
        )}

        <div className="opp-card-meta">
          {opp.location && (
            <span className="opp-card-tag">
              <MapPin size={14} weight="bold" /> {opp.location}
            </span>
          )}
          {opp.role_type && (
            <span className="opp-card-tag">
              <Briefcase size={14} weight="bold" /> {opp.role_type}
            </span>
          )}
          {opp.term_length && (
            <span className="opp-card-tag">
              <Clock size={14} weight="bold" /> {opp.term_length}
            </span>
          )}
        </div>

        <div className="opp-card-footer">
          <a href={opp.url} target="_blank" rel="noreferrer" className="opp-card-link">
            View details &rarr;
          </a>
          <button
            type="button"
            className="opp-inquire-btn"
            onClick={() => onInquire(opp)}
          >
            <EnvelopeSimple size={16} weight="bold" /> Inquire
          </button>
        </div>
      </article>
    </RevealOnScroll>
  );
}

function InquiryModal({ opportunity, onClose }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);

  if (!opportunity) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (supabase) {
      await supabase.from('inquiries').insert({
        opportunity_id: opportunity.id,
        name,
        email,
        message,
        agency: opportunity.agency,
        opportunity_title: opportunity.title
      });
    }
    setSent(true);
  };

  return (
    <div className="opp-modal-overlay" role="presentation" onClick={onClose} onKeyDown={(e) => { if (e.key === 'Escape') onClose(); }}>
      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */}
      <div className="opp-modal" role="dialog" aria-label="Send inquiry" onClick={(e) => e.stopPropagation()}>
        <button type="button" className="opp-modal-close" onClick={onClose} aria-label="Close">
          <X size={20} />
        </button>

        {sent ? (
          <div className="opp-modal-success">
            <h3>Inquiry sent</h3>
            <p>Your interest in <strong>{opportunity.title}</strong> at {opportunity.agency} has been noted. Check your email for next steps.</p>
            <button type="button" className="cta-button" onClick={onClose}>Close</button>
          </div>
        ) : (
          <>
            <h3>Inquire about this opportunity</h3>
            <p className="opp-modal-subtitle">
              <strong>{opportunity.title}</strong> &mdash; {opportunity.agency}
            </p>
            <form onSubmit={handleSubmit} className="opp-inquiry-form">
              <label>
                Name
                <input type="text" value={name} onChange={(e) => setName(e.target.value)} required />
              </label>
              <label>
                Email
                <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </label>
              <label>
                Message
                <textarea
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Tell them a bit about yourself and why this opportunity interests you..."
                />
              </label>
              <button type="submit" className="cta-button">Send inquiry</button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}

export default function OpportunitiesExplorer({ agencyFilter }) {
  const [opportunities, setOpportunities] = useState(BAKED_OPPORTUNITIES);
  const [loading, setLoading] = useState(false);

  // Filters
  const [search, setSearch] = useState('');
  const [selectedAgency, setSelectedAgency] = useState(agencyFilter || '');
  const [selectedRegion, setSelectedRegion] = useState('');
  const [selectedRole, setSelectedRole] = useState('');
  const [selectedTerm, setSelectedTerm] = useState('');
  const [showFilters, setShowFilters] = useState(false);

  // Saved + inquiry
  const [savedIds, setSavedIds] = useState(() => {
    try {
      return new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
    } catch { return new Set(); }
  });
  const [showSavedOnly, setShowSavedOnly] = useState(false);
  const [inquiryOpp, setInquiryOpp] = useState(null);

  useEffect(() => {
    if (!supabase) return;
    let cancelled = false;
    async function refresh() {
      setLoading(true);
      const { data } = await supabase
        .from('opportunities')
        .select('id, agency, title, url, location, region, role_type, term_length, description')
        .eq('active', true)
        .order('agency', { ascending: true })
        .order('title', { ascending: true });
      if (!cancelled && data && data.length > 0) {
        setOpportunities(data);
      }
      setLoading(false);
    }
    refresh();
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    localStorage.setItem('fielded_saved_opps', JSON.stringify([...savedIds]));
  }, [savedIds]);

  const agencies = useMemo(
    () => [...new Set(opportunities.map((o) => o.agency))].sort(),
    [opportunities]
  );

  const filtered = useMemo(() => {
    let list = opportunities;

    if (showSavedOnly) {
      list = list.filter((o) => savedIds.has(o.id));
    }
    if (search) {
      const q = search.toLowerCase();
      list = list.filter((o) =>
        o.title.toLowerCase().includes(q) ||
        (o.description || '').toLowerCase().includes(q) ||
        o.agency.toLowerCase().includes(q) ||
        (o.location || '').toLowerCase().includes(q)
      );
    }
    if (selectedAgency) list = list.filter((o) => o.agency === selectedAgency);
    if (selectedRegion) list = list.filter((o) => o.region === selectedRegion);
    if (selectedRole) list = list.filter((o) => o.role_type === selectedRole);
    if (selectedTerm) list = list.filter((o) => o.term_length === selectedTerm);

    return list;
  }, [opportunities, search, selectedAgency, selectedRegion, selectedRole, selectedTerm, showSavedOnly, savedIds]);

  function toggleSave(id) {
    setSavedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function clearFilters() {
    setSearch('');
    setSelectedAgency('');
    setSelectedRegion('');
    setSelectedRole('');
    setSelectedTerm('');
    setShowSavedOnly(false);
  }

  const hasActiveFilters = search || selectedAgency || selectedRegion || selectedRole || selectedTerm || showSavedOnly;

  return (
    <div className="opp-explorer">
      {/* Search + filter bar */}
      <div className="opp-toolbar">
        <div className="opp-search-wrap">
          <MagnifyingGlass size={18} className="opp-search-icon" />
          <input
            type="search"
            className="opp-search"
            placeholder="Search opportunities..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <button
          type="button"
          className={`opp-filter-toggle${showFilters ? ' opp-filter-toggle--open' : ''}`}
          onClick={() => setShowFilters(!showFilters)}
        >
          <Funnel size={16} weight="bold" />
          Filters
          {hasActiveFilters && <span className="opp-filter-badge" />}
          <CaretDown size={14} className={`opp-caret${showFilters ? ' opp-caret--open' : ''}`} />
        </button>
        <button
          type="button"
          className={`opp-icon-btn opp-saved-toggle${showSavedOnly ? ' opp-icon-btn--saved' : ''}`}
          onClick={() => setShowSavedOnly(!showSavedOnly)}
          aria-label={showSavedOnly ? 'Show all' : 'Show saved only'}
        >
          <Heart weight={showSavedOnly ? 'fill' : 'regular'} size={18} />
          <span className="opp-saved-count">{savedIds.size}</span>
        </button>
      </div>

      {/* Expandable filter panel */}
      {showFilters && (
        <div className="opp-filters">
          <div className="opp-filter-group">
            <span className="opp-filter-label">Agency</span>
            <select value={selectedAgency} onChange={(e) => setSelectedAgency(e.target.value)}>
              <option value="">All agencies</option>
              {agencies.map((a) => <option key={a} value={a}>{a}</option>)}
            </select>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">Region</span>
            <div className="opp-chip-row">
              {REGIONS.map((r) => (
                <FilterChip key={r} label={r} active={selectedRegion === r}
                  onClick={() => setSelectedRegion(selectedRegion === r ? '' : r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">Role type</span>
            <div className="opp-chip-row">
              {ROLE_TYPES.map((r) => (
                <FilterChip key={r} label={r} active={selectedRole === r}
                  onClick={() => setSelectedRole(selectedRole === r ? '' : r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">Term length</span>
            <div className="opp-chip-row">
              {TERM_LENGTHS.map((t) => (
                <FilterChip key={t} label={t} active={selectedTerm === t}
                  onClick={() => setSelectedTerm(selectedTerm === t ? '' : t)} />
              ))}
            </div>
          </div>
          {hasActiveFilters && (
            <button type="button" className="opp-clear-filters" onClick={clearFilters}>
              Clear all filters
            </button>
          )}
        </div>
      )}

      {/* Results */}
      <div className="opp-results-header">
        <p className="opp-results-count">
          {filtered.length} {filtered.length === 1 ? 'opportunity' : 'opportunities'}
          {hasActiveFilters ? ' matching your filters' : ''}
          {loading ? ' (refreshing…)' : ''}
        </p>
      </div>

      {filtered.length === 0 ? (
        <div className="opp-empty">
          <p>No opportunities match your current filters.</p>
          {hasActiveFilters && (
            <button type="button" className="cta-button" onClick={clearFilters}>
              Clear filters
            </button>
          )}
        </div>
      ) : (
        <div className="opp-grid">
          {filtered.map((opp) => (
            <OpportunityCard
              key={opp.id}
              opp={opp}
              saved={savedIds.has(opp.id)}
              onToggleSave={toggleSave}
              onInquire={setInquiryOpp}
            />
          ))}
        </div>
      )}

      <InquiryModal opportunity={inquiryOpp} onClose={() => setInquiryOpp(null)} />
    </div>
  );
}
