// AUTO-GENERATED by scripts/generate-component.js — do not edit by hand.
// Re-run: npm run generate-component
//
// Design tokens applied (from src/styles/tokens.css):
//   --ink-navy: #16233b
//   --atlas-paper: #faf7f0
//   --voyage-teal: #2b6e76
//   --brand-ember: #e0793b
//   --warm-clay: #d98e5c
//   --status-unreached: #b5482f
//   --status-formative: #d9a441
//   --status-reached: #4c8a5e
//   --status-unreached-on-navy: #e0793b
//   --line: rgba(22, 35, 59, 0.15)
//   --muted-text: rgba(22, 35, 59, 0.65)
//   --font-display: 'Fraunces Variable', Georgia, serif
//   --font-body: 'Karla Variable', system-ui, sans-serif
//   --font-mono: 'IBM Plex Mono', 'SFMono-Regular', monospace
//   --font-story-number: 'Recursive Variable', 'IBM Plex Mono', monospace
//   --space-1: 4px
//   --space-2: 8px
//   --space-3: 12px
//   --space-4: 16px
//   --space-6: 24px
//   --space-8: 32px
//   --space-12: 48px
//   --space-16: 64px
//   --radius: 8px
//   --shadow: 0 2px 12px rgba(22, 35, 59, 0.12)
//   --glass-blur: blur(16px) saturate(1.5)
//   --glass-light-bg: rgba(255, 255, 255, 0.45)
//   --glass-light-border: rgba(255, 255, 255, 0.7)
//   --glass-light-sheen: inset 0 1px 0 rgba(255, 255, 255, 0.85)
//   --glass-dark-bg: rgba(250, 247, 240, 0.06)
//   --glass-dark-border: rgba(250, 247, 240, 0.16)
//   --glass-dark-sheen: inset 0 1px 0 rgba(250, 247, 240, 0.14)
//   --glass-shadow: 0 8px 32px rgba(22, 35, 59, 0.18)
//   --focus-ring: 0 0 0 2px var(--atlas-paper), 0 0 0 4px var(--voyage-teal)
//
// Generated: "2026-09-03T20:26:20.819Z"
// Opportunities: 1794 across 34 agencies

import React, { useState, useEffect, useMemo, useRef } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { track } from '@vercel/analytics';
import { MagnifyingGlass, Funnel, Heart, EnvelopeSimple, MapPin, Briefcase, Clock, Info, X, CaretDown, SortAscending, CaretLeft, CaretRight } from '@phosphor-icons/react';
import Fuse from 'fuse.js';
import { supabase } from '../supabaseClient.js';
import RevealOnScroll from './RevealOnScroll.jsx';
import useDebouncedValue from '../hooks/useDebouncedValue.js';
import useJsonLd from '../hooks/useJsonLd.js';

// Reuses the quiz's own scoring output (src/data/scoreAgency.js via
// MatchQuiz.jsx) rather than a second scoring system — CLAUDE.md is explicit
// that getMatches is the one source of "relevance to your quiz" ranking.
const QUIZ_RESULT_KEY = 'fielded_quiz_result';

function loadQuizAgencyScores() {
  try {
    const raw = localStorage.getItem(QUIZ_RESULT_KEY);
    if (!raw) return null;
    const saved = JSON.parse(raw);
    if (!saved || !Array.isArray(saved.matches) || saved.matches.length === 0) return null;
    return new Map(saved.matches.map((m) => [m.name, m.score]));
  } catch {
    return null;
  }
}

const SORT_RELEVANCE = 'relevance';
const SORT_AGENCY = 'agency';
// Neither `scraped_at` nor `date_posted` is a reliable per-listing freshness
// signal (scraped_at is a bulk re-scrape timestamp, date_posted is almost
// always null) — a round-robin interleave by agency is the honest default
// instead of a fabricated "recently added" claim. It also fixes the actual
// bug: raw alphabetical-by-agency reads as an ABWE directory since ABWE
// alone accounts for the first ~250 rows.
const SORT_MIXED = 'mixed';
const SORT_ROLE = 'role';
const SORT_LOCATION = 'location';

// Blank-valued rows sort after every real value (never mixed in
// alphabetically before "A"), then fall back to agency/title so the order
// is still stable and predictable within a tie or an all-blank group.
function sortByField(list, field) {
  return [...list].sort((a, b) => {
    const av = a[field] || '';
    const bv = b[field] || '';
    if (!av && bv) return 1;
    if (av && !bv) return -1;
    return av.localeCompare(bv) || a.agency.localeCompare(b.agency) || a.title.localeCompare(b.title);
  });
}

const PAGE_SIZE = 24;

// Missions-world terminology where the "obvious" search word and the word
// actually likely to appear in a listing's title/role_type/description
// aren't the same string — e.g. someone searching "Muslim" should also
// surface listings that only say "Islam" or "Islamic", and "BAM" (Business
// as Mission) is standard shorthand for what a listing's own text usually
// calls "creative access". Case-insensitive, matched by whole-term equality
// (not fuzzy) against the term the user typed, then every synonym in the
// matched group is OR'd together (see expandSearchTerm) before that group's
// result set gets intersected with any other search term, same as always.
const SYNONYM_GROUPS = [
  ['islam', 'muslim', 'islamic'],
  ['bam', 'business as mission', 'creative access', 'restricted access'],
  ['upg', 'unreached', 'unreached people group'],
  ['tck', 'third culture kid'],
  ['esl', 'tesol', 'efl', 'english teaching']
];

function expandSearchTerm(term) {
  const lower = term.trim().toLowerCase();
  const group = SYNONYM_GROUPS.find((g) => g.includes(lower));
  return group ? [term, ...group] : [term];
}

// One item from each agency bucket per round, cycling until every bucket is
// exhausted — turns "first 250 rows are all ABWE" into "one ABWE listing
// every ~22 opportunities." Bucket order follows first-appearance order in
// `list` (which is itself agency-alphabetical from the source query), so the
// interleave is still deterministic and stable across renders.
function interleaveByAgency(list) {
  const buckets = new Map();
  for (const o of list) {
    if (!buckets.has(o.agency)) buckets.set(o.agency, []);
    buckets.get(o.agency).push(o);
  }
  const bucketArrays = [...buckets.values()];
  const result = [];
  let i = 0;
  while (result.length < list.length) {
    for (const bucket of bucketArrays) {
      if (i < bucket.length) result.push(bucket[i]);
    }
    i += 1;
  }
  return result;
}

// Parses a comma-separated query-param value into a Set, or an empty Set if
// the param is absent — used for every multi-select filter's URL sync.
function parseSetParam(params, key) {
  const raw = params.get(key);
  return raw ? new Set(raw.split(',').filter(Boolean)) : new Set();
}

// The full opportunities list used to be inlined here as a literal — with
// 1500+ records that made this one file (and its route chunk) ~650KB before
// gzip, dwarfing every other route. It's now a static JSON asset fetched at
// runtime instead, matching the pattern already used for the world map's
// people-groups data (see WorldMap.jsx) — same-origin, CDN-cached, and still
// resilient to Supabase specifically being unreachable, which is what this
// fallback is actually for.
//
// The static snapshot is the primary data source on every load (one 568KB
// CDN-cached fetch). Supabase is only consulted as an optional background
// freshness check, gated by VITE_ENABLE_FRESH_FETCH — every visit used to
// fire two sequential 1000-row Supabase queries on top of the static fetch,
// which is 1,500+ rows downloaded for data the static snapshot already had.
const FALLBACK_URL = '/data/opportunities-fallback.json';
const ENABLE_FRESH_FETCH = import.meta.env.VITE_ENABLE_FRESH_FETCH === 'true';

const REGIONS = [
  "Central Asia",
  "East Asia",
  "Europe",
  "Islands / Oceania",
  "Latin America",
  "Middle East / North Africa",
  "North America",
  "Oceania",
  "Oceania / Asia-Pacific",
  "South Asia",
  "Southeast Asia",
  "Sub-Saharan Africa"
];
const ROLE_TYPES = [
  "Bible translation/linguistics",
  "administration",
  "aviation/logistics",
  "business as mission",
  "children/youth ministry",
  "church planting",
  "construction/maintenance",
  "discipleship training",
  "education/TESOL",
  "evangelism/discipleship",
  "internship",
  "media/creative",
  "medical",
  "member care",
  "mobilization",
  "prayer",
  "relief and development",
  "research",
  "short-term missions",
  "sports ministry",
  "staff/leadership",
  "technology",
  "theological education",
  "training/leadership",
  "volunteer"
];
const TERM_LENGTHS = [
  "short-term (under 2 years)",
  "mid-term (2-4 years)",
  "career/long-term"
];

// Opportunities carry only a coarse `region` string, not coordinates or a
// country code, so "10/40 Window" (the ~10-40°N band spanning North Africa,
// the Middle East, and Asia) can only be approximated by which of our
// existing region buckets fall inside it — not computed precisely. Chosen
// deliberately over Sub-Saharan Africa (mostly south of 10°N), Europe,
// Latin America, North America, and Oceania, none of which are part of the
// window.
const WINDOW_1040_REGIONS = ['Middle East / North Africa', 'Central Asia', 'South Asia', 'Southeast Asia', 'East Asia'];

// "Inquire" needs an object — but agency names are a mix of shapes
// ("ABWE", "Africa Inland Mission (AIM)", "Cru (Campus Crusade for
// Christ)"), so a blind "text in parens" extraction would turn Cru into
// "Inquire with Campus Crusade for Christ." Only treats the parenthetical
// as the short name when it actually looks like an acronym (all caps,
// 2-6 letters) — otherwise falls back to the text before the parens, and
// falls back to the full name when there's no parenthetical at all. Never
// invents an abbreviation that isn't already present in the source name.
function shortAgencyName(agency) {
  const match = agency.match(/^(.*?)\s*\(([^)]+)\)\s*$/);
  if (!match) return agency;
  const [, before, paren] = match;
  return /^[A-Z]{2,6}$/.test(paren) ? paren : before.trim();
}

// Mirrors the literal generateFallbackDescription() produces in
// scripts/lib/sanitize.js — a listing whose description IS that generated
// one-liner has real fields (it already passed ingestion validation) but no
// actual scraped text, either because the agency page never had any or
// because what it did have was too long to quote without reproducing the
// agency's own copy verbatim (see isTooLongToQuote). Either way, there's
// nothing here beyond "click through and ask" — worth telling users that
// before they click, not after. Both need updating together if that
// generated string ever changes.
const THIN_DESCRIPTION_MARKER = 'Reach out to the agency directly for full role details.';

function isThinListing(opp) {
  return !opp.description || opp.description.includes(THIN_DESCRIPTION_MARKER);
}

function FilterChip({ label, active, count, onClick }) {
  return (
    <button
      type="button"
      className={`opp-filter-chip${active ? ' opp-filter-chip--active' : ''}`}
      aria-pressed={active}
      onClick={onClick}
    >
      <span>{label}</span>
      {count > 0 && <span className="opp-filter-chip-count">({count.toLocaleString()})</span>}
    </button>
  );
}

function OpportunityCard({ opp, saved, onToggleSave, onInquire }) {
  const thin = isThinListing(opp);
  return (
    <RevealOnScroll className="opp-card-wrapper">
      <article className="opp-card">
        <div className="opp-card-header">
          <span className="opp-card-agency">{opp.agency}</span>
          <div className="opp-card-actions">
            <button
              type="button"
              className={`opp-icon-btn${saved ? ' opp-icon-btn--saved' : ''}`}
              onClick={() => onToggleSave(opp.id)}
              aria-label={saved ? 'Remove from saved' : 'Save opportunity'}
            >
              <Heart weight={saved ? 'fill' : 'regular'} size={18} />
            </button>
          </div>
        </div>

        <h2 className="opp-card-title">{opp.title}</h2>

        {opp.description && (
          <p className="opp-card-desc">{opp.description}</p>
        )}

        <div className="opp-card-meta">
          {opp.location && (
            <span className="opp-card-tag">
              <MapPin size={14} weight="bold" /> {opp.location}
            </span>
          )}
          {opp.role_type && (
            <span className="opp-card-tag">
              <Briefcase size={14} weight="bold" /> {opp.role_type}
            </span>
          )}
          {opp.term_length && (
            <span className="opp-card-tag">
              <Clock size={14} weight="bold" /> {opp.term_length}
            </span>
          )}
          {thin && (
            <span className="opp-card-tag opp-card-tag--thin">
              <Info size={14} weight="bold" /> Few details — check the agency's site
            </span>
          )}
        </div>

        <div className="opp-card-footer">
          <a
            href={opp.url}
            target="_blank"
            rel="noreferrer"
            className="opp-card-link"
            onClick={() => track('opportunity_clickthrough', { opportunityId: opp.id, agency: opp.agency })}
          >
            View details &rarr;
          </a>
          <button
            type="button"
            className="opp-inquire-btn"
            onClick={() => onInquire(opp)}
          >
            <EnvelopeSimple size={16} weight="bold" /> Inquire with {shortAgencyName(opp.agency)}
          </button>
        </div>
      </article>
    </RevealOnScroll>
  );
}

function InquiryModal({ opportunity, onClose }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);
  const modalRef = useRef(null);
  const closeButtonRef = useRef(null);
  const triggerRef = useRef(null);

  // Opens: move focus into the dialog (the close button, always present
  // whether or not `sent`) and remember whatever had focus before, since
  // that's what "Inquire with {agency}" was. Closes: focus goes back there —
  // without this, a keyboard/screen-reader user closing the modal lands
  // wherever the DOM cursor happens to be, not back where they were.
  useEffect(() => {
    if (!opportunity) return;
    triggerRef.current = document.activeElement;
    closeButtonRef.current?.focus();
    return () => triggerRef.current?.focus?.();
  }, [opportunity]);

  if (!opportunity) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (supabase) {
      await supabase.from('inquiries').insert({
        opportunity_id: opportunity.id,
        name,
        email,
        message,
        agency: opportunity.agency,
        opportunity_title: opportunity.title
      });
    }
    setSent(true);
  };

  // Escape closes (as before); Tab/Shift+Tab wraps focus at the dialog's own
  // edges instead of escaping into the page behind it — a modal with
  // aria-modal="true" but no actual focus trap tells assistive tech one
  // thing and lets sighted-mouse-free keyboard users do another.
  const handleKeyDown = (e) => {
    if (e.key === 'Escape') {
      onClose();
      return;
    }
    if (e.key !== 'Tab') return;
    const focusable = modalRef.current?.querySelectorAll(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    if (!focusable || focusable.length === 0) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    if (e.shiftKey && document.activeElement === first) {
      e.preventDefault();
      last.focus();
    } else if (!e.shiftKey && document.activeElement === last) {
      e.preventDefault();
      first.focus();
    }
  };

  return (
    <div className="opp-modal-overlay" role="presentation" onClick={onClose} onKeyDown={handleKeyDown}>
      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */}
      <div className="opp-modal" role="dialog" aria-modal="true" aria-label="Send inquiry" ref={modalRef} onClick={(e) => e.stopPropagation()}>
        <button type="button" className="opp-modal-close" onClick={onClose} aria-label="Close" ref={closeButtonRef}>
          <X size={20} />
        </button>

        {sent ? (
          <div className="opp-modal-success">
            <h3>Inquiry sent</h3>
            <p>Your interest in <strong>{opportunity.title}</strong> at {opportunity.agency} has been noted. Check your email for next steps.</p>
            <button type="button" className="cta-button" onClick={onClose}>Close</button>
          </div>
        ) : (
          <>
            <h3>Inquire about this opportunity</h3>
            <p className="opp-modal-subtitle">
              <strong>{opportunity.title}</strong> &mdash; {opportunity.agency}
            </p>
            <form onSubmit={handleSubmit} className="opp-inquiry-form">
              <label>
                Name
                <input type="text" value={name} onChange={(e) => setName(e.target.value)} required />
              </label>
              <label>
                Email
                <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </label>
              <label>
                Message
                <textarea
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Tell them a bit about yourself and why this opportunity interests you..."
                />
              </label>
              <button type="submit" className="cta-button">Send inquiry</button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}

export default function OpportunitiesExplorer({ agencyFilter }) {
  // null = not loaded yet (distinct from "loaded, zero results" so the
  // empty-filters copy doesn't flash for a normal loading heartbeat).
  const [opportunities, setOpportunities] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState(false);
  const [fallbackError, setFallbackError] = useState(false);

  // Page, filters, and sort all live in the URL (?page=2&agency=ABWE&category=medical)
  // so results are shareable and survive a reload — read once on mount as the
  // initial state, then kept in sync by the effect below on every change.
  const [searchParams, setSearchParams] = useSearchParams();

  // Filters — Sets for multi-select (union/OR within a category, intersection/AND across categories)
  // `search` is the live, uncommitted text box value; pressing Enter commits
  // it into `searchTerms`, a stack of independent search chips that are all
  // ANDed together (see matchedIds below) — each added term can only narrow
  // the result set further, never widen it, same intersection model the
  // agency/region/role/term filters already use.
  const [search, setSearch] = useState(() => searchParams.get('q') || '');
  const [searchTerms, setSearchTerms] = useState(() => searchParams.getAll('sq'));
  const [selectedAgencies, setSelectedAgencies] = useState(() => {
    const fromUrl = parseSetParam(searchParams, 'agency');
    if (fromUrl.size > 0) return fromUrl;
    return agencyFilter ? new Set([agencyFilter]) : new Set();
  });
  const [selectedRegions, setSelectedRegions] = useState(() => parseSetParam(searchParams, 'region'));
  // URL param is named `category` (not `role`) to match the audit spec's
  // example (`?category=medical`) — it maps to the role_type field.
  const [selectedRoles, setSelectedRoles] = useState(() => parseSetParam(searchParams, 'category'));
  const [selectedTerms, setSelectedTerms] = useState(() => parseSetParam(searchParams, 'term'));
  const [show1040Only, setShow1040Only] = useState(() => searchParams.get('window1040') === '1');
  const [showFilters, setShowFilters] = useState(false);
  const filtersPanelRef = useRef(null);
  const filterToggleRef = useRef(null);

  const [quizScores] = useState(loadQuizAgencyScores);
  const [sortMode, setSortMode] = useState(() => {
    const fromUrl = searchParams.get('sort');
    if (fromUrl === SORT_AGENCY || fromUrl === SORT_ROLE || fromUrl === SORT_LOCATION || (fromUrl === SORT_RELEVANCE && quizScores)) return fromUrl;
    if (fromUrl === SORT_MIXED) return SORT_MIXED;
    return quizScores ? SORT_RELEVANCE : SORT_MIXED;
  });
  const [page, setPage] = useState(() => Math.max(1, parseInt(searchParams.get('page'), 10) || 1));

  // Promotes the current text box value into its own permanent search chip
  // (deduped) and clears the box for the next term — this is what lets
  // someone stack "medical" + "Kenya" as two independent, intersected
  // filters instead of one search replacing the last.
  function commitSearchTerm() {
    const term = search.trim();
    if (!term) return;
    setSearchTerms((prev) => (prev.includes(term) ? prev : [...prev, term]));
    setSearch('');
  }

  function removeSearchTerm(term) {
    setSearchTerms((prev) => prev.filter((t) => t !== term));
  }

  function toggleFilter(setter, value) {
    setter(prev => {
      const next = new Set(prev);
      if (next.has(value)) next.delete(value);
      else next.add(value);
      return next;
    });
  }

  // Saved + inquiry
  const [savedIds, setSavedIds] = useState(() => {
    try {
      return new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
    } catch { return new Set(); }
  });
  const [showSavedOnly, setShowSavedOnly] = useState(false);
  const [inquiryOpp, setInquiryOpp] = useState(null);

  // Signed-out: favorites are device-owned, in localStorage (savedIds above).
  // Signed-in: Supabase's saved_opportunities table is the source of truth,
  // so favorites follow the user across devices. The two are merged (union,
  // never a wholesale overwrite) the moment a session first appears.
  const [session, setSession] = useState(null);

  // Loads the static fallback snapshot once on mount. Only applies it if
  // nothing has been set yet — if the live Supabase fetch below already won
  // the race, this must never clobber fresher data with the stale snapshot.
  useEffect(() => {
    let cancelled = false;
    fetch(FALLBACK_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        setOpportunities((prev) => (prev === null ? data : prev));
      })
      .catch((err) => {
        if (cancelled) return;
        console.error('Failed to load the opportunities fallback snapshot:', err);
        setFallbackError(true);
      });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    if (!supabase || !ENABLE_FRESH_FETCH) return;
    let cancelled = false;
    async function refresh() {
      setLoading(true);
      setLoadError(false);
      const allRows = [];
      const PAGE_SIZE = 1000;
      let from = 0;
      try {
        while (true) {
          const { data, error } = await supabase
            .from('opportunities')
            .select('id, agency, title, url, location, region, role_type, term_length, description')
            .eq('active', true)
            .order('agency', { ascending: true })
            .order('title', { ascending: true })
            .range(from, from + PAGE_SIZE - 1);
          if (cancelled) return;
          if (error) throw error;
          allRows.push(...(data || []));
          if (!data || data.length < PAGE_SIZE) break;
          from += PAGE_SIZE;
        }
        if (!cancelled && allRows.length > 0) {
          setOpportunities(allRows);
        }
      } catch (err) {
        if (cancelled) return;
        // Network hiccup or RLS misconfig — leave whatever the fallback
        // effect already loaded (or will load) in place rather than an
        // empty list, but surface it so a stale-data banner can render and
        // so this shows up in error monitoring instead of failing silently.
        console.error('Failed to load live opportunities, showing cached snapshot:', err);
        setLoadError(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    refresh();
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    localStorage.setItem('fielded_saved_opps', JSON.stringify([...savedIds]));
  }, [savedIds]);

  useEffect(() => {
    if (!supabase) return;
    supabase.auth.getSession().then(({ data }) => setSession(data.session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, newSession) => {
      setSession(newSession);
    });
    return () => listener.subscription.unsubscribe();
  }, []);

  // First sign-in: merge whatever was saved locally (signed-out browsing)
  // with whatever's already in Supabase for this user, so neither side gets
  // clobbered. Keyed on the user id, not the session object itself, since
  // onAuthStateChange also fires (with a new session object) on token
  // refresh — that must not re-run the merge on every refresh.
  const userId = session?.user?.id;
  useEffect(() => {
    if (!supabase || !userId) return;
    let cancelled = false;
    async function mergeFavorites() {
      const { data, error } = await supabase
        .from('saved_opportunities')
        .select('opportunity_id')
        .eq('user_id', userId);
      if (cancelled) return;
      if (error) {
        console.error('Failed to load saved opportunities from Supabase:', error);
        return;
      }
      const remoteIds = new Set((data || []).map((r) => r.opportunity_id));
      let localIds = new Set();
      try {
        localIds = new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
      } catch {
        // ignore malformed cache
      }
      const missingFromRemote = [...localIds].filter((id) => !remoteIds.has(id));
      if (missingFromRemote.length > 0) {
        const { error: upsertError } = await supabase
          .from('saved_opportunities')
          .upsert(missingFromRemote.map((id) => ({ user_id: userId, opportunity_id: id })), {
            onConflict: 'user_id,opportunity_id'
          });
        if (upsertError) console.error('Failed to merge local favorites into Supabase:', upsertError);
      }
      if (!cancelled) setSavedIds(new Set([...remoteIds, ...localIds]));
    }
    mergeFavorites();
    return () => { cancelled = true; };
  }, [userId]);

  const agencies = useMemo(
    () => [...new Set((opportunities || []).map((o) => o.agency))].sort(),
    [opportunities]
  );

  // Debounced so a Fuse re-search over 1,000+ records runs once per pause in
  // typing rather than on every keystroke — the list is already in memory
  // (static snapshot fetched once on mount), so this is purely to avoid
  // re-scoring the whole set on each keypress, not to avoid a network call.
  const debouncedSearch = useDebouncedValue(search, 350);

  // One Fuse index over the full in-memory list, rebuilt only when the
  // opportunities set itself changes (initial load / live-fetch swap) — not
  // on every keystroke or filter change. Weighted so a title/agency match
  // ranks above a match buried in the description.
  const searchIndex = useMemo(
    () =>
      new Fuse(opportunities || [], {
        keys: [
          { name: 'title', weight: 0.35 },
          { name: 'agency', weight: 0.25 },
          { name: 'role_type', weight: 0.15 },
          { name: 'location', weight: 0.15 },
          { name: 'description', weight: 0.1 }
        ],
        threshold: 0.32,
        ignoreLocation: true
      }),
    [opportunities]
  );

  // null = no active search (every row passes); otherwise the set of ids
  // Fuse matched, so search can be intersected with every other filter via
  // a plain Set.has() the same way agency/region/role/term already are —
  // that's what makes search narrow within the current filter selection
  // rather than replace it.
  //
  // Every committed search chip PLUS whatever's still being typed (the
  // debounced draft) is Fused independently, then the per-term id sets are
  // intersected — an opportunity has to match every term to survive, so
  // each additional chip can only shrink the result set, never grow it.
  //
  // Within a single term, synonyms (see SYNONYM_GROUPS/expandSearchTerm
  // above) are the opposite: OR'd together first, since "Muslim" and
  // "Islam" are the same search intent, not two separate narrowing
  // filters — only after that union is a term's result set intersected
  // with every other term's.
  const matchedIds = useMemo(() => {
    const terms = [...searchTerms];
    const draft = debouncedSearch.trim();
    if (draft) terms.push(draft);
    if (terms.length === 0) return null;

    return terms
      .map((term) => {
        const ids = new Set();
        for (const variant of expandSearchTerm(term)) {
          for (const r of searchIndex.search(variant)) ids.add(r.item.id);
        }
        return ids;
      })
      .reduce((a, b) => new Set([...a].filter((id) => b.has(id))));
  }, [searchIndex, searchTerms, debouncedSearch]);

  // Every filter dimension applied except `search`/`showSavedOnly` (which
  // apply everywhere) and whichever dimension `skipKey` names — that's what
  // makes a facet count reflect "how many results if I also picked this
  // option", not "how many results right now" (which would just repeat the
  // header count on every chip and zero out sibling options in the same
  // group the instant one is selected).
  function baseFilteredList(list, skipKey) {
    // Category pages ("Serve in Albania", "{Category} — Avant") aren't
    // individual openings — sanitize.js (P1-C) flags them via listing_type
    // so they're excluded from the default list rather than padding it with
    // entries that don't represent a real, distinct role.
    let out = list.filter((o) => o.listing_type !== 'category_page');
    if (showSavedOnly) out = out.filter((o) => savedIds.has(o.id));
    if (matchedIds) out = out.filter((o) => matchedIds.has(o.id));
    if (skipKey !== 'agency' && selectedAgencies.size > 0) out = out.filter((o) => selectedAgencies.has(o.agency));
    if (skipKey !== 'region' && selectedRegions.size > 0) out = out.filter((o) => selectedRegions.has(o.region));
    if (skipKey !== 'role' && selectedRoles.size > 0) out = out.filter((o) => selectedRoles.has(o.role_type));
    if (skipKey !== 'term' && selectedTerms.size > 0) out = out.filter((o) => selectedTerms.has(o.term_length));
    if (skipKey !== 'window1040' && show1040Only) out = out.filter((o) => WINDOW_1040_REGIONS.includes(o.region));
    return out;
  }

  function countBy(list, field) {
    const counts = new Map();
    for (const o of list) {
      const v = o[field];
      if (v == null) continue;
      counts.set(v, (counts.get(v) || 0) + 1);
    }
    return counts;
  }

  const agencyCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'agency'), 'agency'),
    [opportunities, matchedIds, selectedRegions, selectedRoles, selectedTerms, show1040Only, showSavedOnly, savedIds]
  );
  const regionCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'region'), 'region'),
    [opportunities, matchedIds, selectedAgencies, selectedRoles, selectedTerms, show1040Only, showSavedOnly, savedIds]
  );
  const roleCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'role'), 'role_type'),
    [opportunities, matchedIds, selectedAgencies, selectedRegions, selectedTerms, show1040Only, showSavedOnly, savedIds]
  );
  const termCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'term'), 'term_length'),
    [opportunities, matchedIds, selectedAgencies, selectedRegions, selectedRoles, show1040Only, showSavedOnly, savedIds]
  );
  const window1040Count = useMemo(
    () => baseFilteredList(opportunities || [], 'window1040').filter((o) => WINDOW_1040_REGIONS.includes(o.region)).length,
    [opportunities, matchedIds, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, showSavedOnly, savedIds]
  );

  const filtered = useMemo(() => {
    let list = baseFilteredList(opportunities || [], null);

    if (sortMode === SORT_AGENCY) {
      list = [...list].sort((a, b) => a.agency.localeCompare(b.agency) || a.title.localeCompare(b.title));
    } else if (sortMode === SORT_ROLE) {
      list = sortByField(list, 'role_type');
    } else if (sortMode === SORT_LOCATION) {
      list = sortByField(list, 'location');
    } else if (sortMode === SORT_RELEVANCE && quizScores) {
      list = [...list].sort((a, b) => (quizScores.get(b.agency) ?? -1) - (quizScores.get(a.agency) ?? -1));
    } else {
      // SORT_MIXED (default): round-robin interleave by agency — see
      // interleaveByAgency() above for why this replaces raw alphabetical.
      list = interleaveByAgency(list);
    }

    return list;
  }, [opportunities, matchedIds, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, show1040Only, showSavedOnly, savedIds, sortMode, quizScores]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const pageItems = useMemo(
    () => filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE),
    [filtered, page]
  );

  // Built from pageItems — the same cards actually rendered below, not the
  // full 1,220-row dataset — so this always matches what's really on the
  // page (including the default/no-filter view a crawler's first hit sees)
  // rather than claiming a list the response doesn't contain. `null` while
  // there's nothing to list yet (still loading, or a filtered/search result
  // came back empty) so useJsonLd removes the tag instead of emitting an
  // empty itemListElement.
  const opportunitiesListSchema = useMemo(() => {
    if (pageItems.length === 0) return null;
    return {
      '@context': 'https://schema.org',
      '@type': 'ItemList',
      itemListElement: pageItems.map((opp, i) => ({
        '@type': 'ListItem',
        position: (page - 1) * PAGE_SIZE + i + 1,
        url: opp.url,
        name: opp.title
      }))
    };
  }, [pageItems, page]);
  useJsonLd('opportunities-list', opportunitiesListSchema);

  // JobPosting per listing, built only from fields the scraped data
  // actually has. Deliberately missing Google's `datePosted` (a required
  // field for Job rich results) — neither the ingestion pipeline nor the
  // agency pages it scrapes expose a real per-listing post date, only a
  // bulk `created_at` re-scrape timestamp (see SORT_MIXED above for the
  // same honesty call on a different feature). Using that as `datePosted`
  // would misrepresent when the role was actually posted, so it's left out
  // rather than guessed — this markup is valid schema.org JobPosting data
  // and still useful context for general indexing, but won't itself
  // qualify for Google's Job experience without a real posting date.
  // `employmentType` is skipped for the same reason: term_length describes
  // a commitment *duration* ("short-term (under 2 years)"), not an
  // employmentType classification (FULL_TIME/CONTRACTOR/VOLUNTEER/...) —
  // forcing one into the other would be a category error, not just an
  // approximation. `baseSalary` is skipped because these roles are
  // typically support-raised, not salaried — there's no real figure to
  // report. Listings with neither `location` nor `region` are excluded
  // entirely rather than emitted without `jobLocation` (also required):
  // same "render nothing rather than an incomplete/guessed field" rule
  // CLAUDE.md already states for agency data elsewhere in this app.
  const jobPostingSchema = useMemo(() => {
    const withLocation = pageItems.filter((opp) => opp.location || opp.region);
    if (withLocation.length === 0) return null;
    return {
      '@context': 'https://schema.org',
      '@graph': withLocation.map((opp) => ({
        '@type': 'JobPosting',
        identifier: { '@type': 'PropertyValue', name: 'Fielded', value: opp.id },
        title: opp.title,
        description: opp.description,
        url: opp.url,
        hiringOrganization: { '@type': 'Organization', name: opp.agency },
        jobLocation: {
          '@type': 'Place',
          address: { '@type': 'PostalAddress', addressLocality: opp.location || opp.region }
        }
      }))
    };
  }, [pageItems]);
  useJsonLd('opportunities-jobs', jobPostingSchema);

  // Reset to page 1 whenever the result set could have changed shape —
  // search, filters, or sort — but not on first mount, so a shared/reloaded
  // URL like ?page=3&agency=ABWE actually lands on page 3 instead of always
  // snapping back to page 1.
  const isFirstFilterRender = useRef(true);
  useEffect(() => {
    if (isFirstFilterRender.current) {
      isFirstFilterRender.current = false;
      return;
    }
    setPage(1);
  }, [search, searchTerms, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, sortMode, showSavedOnly]);

  // Clamp if filters shrank the result set out from under the current page
  // (e.g. on page 5 of "ABWE", then also filter to a term length with none).
  // Skipped while opportunities is still null — otherwise totalPages is
  // briefly 1 (nothing loaded yet) and this would snap a URL-provided
  // ?page=3 back down to 1 before the real data ever arrives.
  useEffect(() => {
    if (opportunities === null) return;
    if (page > totalPages) setPage(totalPages);
  }, [opportunities, page, totalPages]);

  // URL is the single source of truth for "what am I looking at" — every
  // page/filter/sort change re-serializes here so results stay shareable and
  // reloadable. `replace: true` avoids piling one history entry per
  // keystroke in the search box; Prev/Next/page-number clicks still update
  // this same URL (browser back still works, just steps over the whole
  // filter state rather than one field at a time).
  useEffect(() => {
    const next = new URLSearchParams();
    if (search) next.set('q', search);
    for (const term of searchTerms) next.append('sq', term);
    if (selectedAgencies.size > 0) next.set('agency', [...selectedAgencies].join(','));
    if (selectedRegions.size > 0) next.set('region', [...selectedRegions].join(','));
    if (selectedRoles.size > 0) next.set('category', [...selectedRoles].join(','));
    if (selectedTerms.size > 0) next.set('term', [...selectedTerms].join(','));
    if (show1040Only) next.set('window1040', '1');
    if (showSavedOnly) next.set('saved', '1');
    if (sortMode !== SORT_MIXED) next.set('sort', sortMode);
    if (page > 1) next.set('page', String(page));
    setSearchParams(next, { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search, searchTerms, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, show1040Only, showSavedOnly, sortMode, page]);

  function toggleSave(id) {
    const wasSaved = savedIds.has(id);
    setSavedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

    if (!wasSaved) track('opportunity_saved', { opportunityId: id });

    // Signed in: Supabase is the source of truth, so the edit goes there
    // (and follows the user across devices). Signed out: the localStorage
    // effect above is the only persistence, same as before this feature.
    if (supabase && userId) {
      const write = wasSaved
        ? supabase.from('saved_opportunities').delete().match({ user_id: userId, opportunity_id: id })
        : supabase.from('saved_opportunities').upsert(
            { user_id: userId, opportunity_id: id },
            { onConflict: 'user_id,opportunity_id' }
          );
      write.then(({ error }) => {
        if (error) console.error('Failed to sync saved opportunity to Supabase:', error);
      });
    }
  }

  function openInquiry(opp) {
    track('opportunity_inquiry_opened', { opportunityId: opp.id });
    setInquiryOpp(opp);
  }

  function clearFilters() {
    setSearch('');
    setSearchTerms([]);
    setSelectedAgencies(new Set());
    setSelectedRegions(new Set());
    setSelectedRoles(new Set());
    setSelectedTerms(new Set());
    setShow1040Only(false);
    setShowSavedOnly(false);
  }

  const activeFilterCount = selectedAgencies.size + selectedRegions.size + selectedRoles.size + selectedTerms.size + (show1040Only ? 1 : 0);
  const hasActiveFilters = search || searchTerms.length > 0 || activeFilterCount > 0 || showSavedOnly;

  // Removable-chip summary of every active filter, independent of whether
  // the filter panel itself is open — a visitor shouldn't have to reopen
  // the panel just to see (or undo) what's currently narrowing the list.
  const activeFilterChips = useMemo(() => {
    const chips = [];
    for (const term of searchTerms) chips.push({ key: `search-${term}`, label: `"${term}"`, onRemove: () => removeSearchTerm(term) });
    if (search) chips.push({ key: 'search-draft', label: `"${search}"`, onRemove: () => setSearch('') });
    for (const a of selectedAgencies) chips.push({ key: `agency-${a}`, label: a, onRemove: () => toggleFilter(setSelectedAgencies, a) });
    for (const r of selectedRegions) chips.push({ key: `region-${r}`, label: r, onRemove: () => toggleFilter(setSelectedRegions, r) });
    for (const r of selectedRoles) chips.push({ key: `role-${r}`, label: r, onRemove: () => toggleFilter(setSelectedRoles, r) });
    for (const t of selectedTerms) chips.push({ key: `term-${t}`, label: t, onRemove: () => toggleFilter(setSelectedTerms, t) });
    if (show1040Only) chips.push({ key: 'window1040', label: '10/40 Window', onRemove: () => setShow1040Only(false) });
    if (showSavedOnly) chips.push({ key: 'saved', label: 'Saved only', onRemove: () => setShowSavedOnly(false) });
    return chips;
  }, [search, searchTerms, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, show1040Only, showSavedOnly]);

  // Below ~640px the filter panel becomes a bottom sheet (see .opp-filters
  // in styles.css) — this gives it the keyboard behavior a sheet actually
  // needs (focus moves in on open, Tab wraps at its own edges, Escape
  // closes and returns focus to the toggle that opened it), matching
  // InquiryModal's pattern. Above 640px it stays the existing inline
  // region — a real focus trap there would be a regression, not an
  // improvement, since the rest of the page is still fully usable while
  // it's open — so the trap itself only activates under the same
  // 640px breakpoint the CSS uses.
  useEffect(() => {
    if (!showFilters) return;
    const isMobile = window.matchMedia('(max-width: 640px)').matches;
    if (isMobile) {
      const focusable = filtersPanelRef.current?.querySelector(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      );
      focusable?.focus();
    }
    function handleKeyDown(e) {
      if (e.key === 'Escape') {
        setShowFilters(false);
        filterToggleRef.current?.focus();
        return;
      }
      if (!isMobile || e.key !== 'Tab') return;
      const focusables = filtersPanelRef.current?.querySelectorAll(
        'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
      );
      if (!focusables || focusables.length === 0) return;
      const first = focusables[0];
      const last = focusables[focusables.length - 1];
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    }
    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [showFilters]);

  return (
    <div className="opp-explorer">
      {/* Search + filter bar */}
      <div className="opp-toolbar">
        <div className="opp-search-wrap">
          <MagnifyingGlass size={18} className="opp-search-icon" />
          <input
            // type="text" with an explicit role rather than type="search" —
            // sidesteps the native browser affordances (its own clear-icon,
            // autofill/history dropdown) that come with type="search" and
            // aren't needed here, since commitSearchTerm below already
            // fully owns clearing the box. role="searchbox" keeps the same
            // accessible semantics screen readers would get from the native
            // type either way.
            type="text"
            role="searchbox"
            className="opp-search"
            placeholder="Search opportunities..."
            aria-label="Search opportunities"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault();
                commitSearchTerm();
              }
            }}
          />
        </div>
        <button
          type="button"
          ref={filterToggleRef}
          className={`opp-filter-toggle${showFilters ? ' opp-filter-toggle--open' : ''}`}
          onClick={() => setShowFilters(!showFilters)}
          aria-expanded={showFilters}
          aria-controls="opp-filters-panel"
        >
          <Funnel size={16} weight="bold" />
          Filters
          {activeFilterCount > 0 && <span className="opp-filter-badge">{activeFilterCount}</span>}
          <CaretDown size={14} className={`opp-caret${showFilters ? ' opp-caret--open' : ''}`} />
        </button>
        <button
          type="button"
          className={`opp-icon-btn opp-saved-toggle${showSavedOnly ? ' opp-icon-btn--saved' : ''}`}
          onClick={() => setShowSavedOnly(!showSavedOnly)}
          aria-label={showSavedOnly ? 'Show all' : 'Show saved only'}
        >
          <Heart weight={showSavedOnly ? 'fill' : 'regular'} size={18} />
          <span className="opp-saved-count">{savedIds.size}</span>
        </button>
        <label className="opp-sort">
          <SortAscending size={16} weight="bold" />
          <span className="visually-hidden">Sort opportunities by</span>
          <select
            className="opp-sort-select"
            value={sortMode}
            onChange={(e) => setSortMode(e.target.value)}
          >
            {quizScores && <option value={SORT_RELEVANCE}>Relevance</option>}
            <option value={SORT_AGENCY}>Agency A–Z</option>
            <option value={SORT_MIXED}>All agencies (mixed)</option>
            <option value={SORT_ROLE}>Role type A–Z</option>
            <option value={SORT_LOCATION}>Location A–Z</option>
          </select>
        </label>
      </div>

      {activeFilterChips.length > 0 && (
        <div className="opp-active-filters" aria-label="Active filters">
          {activeFilterChips.map((chip) => (
            <button type="button" key={chip.key} className="opp-active-chip" onClick={chip.onRemove}>
              <span>{chip.label}</span>
              <X size={12} weight="bold" aria-hidden="true" />
              <span className="visually-hidden">Remove filter</span>
            </button>
          ))}
          <button type="button" className="opp-clear-filters opp-clear-filters--inline" onClick={clearFilters}>
            Clear all
          </button>
        </div>
      )}

      {sortMode === SORT_RELEVANCE && quizScores ? (
        <p className="opp-sort-pill">Sorted by your quiz matches</p>
      ) : !quizScores ? (
        <p className="opp-sort-hint">
          <Link to="/quiz">Start with a quick quiz</Link> to find your best fit — opportunities can then sort by relevance to your answers.
        </p>
      ) : null}

      {/* Expandable filter panel — an inline region on desktop, a bottom
          sheet below 640px (see .opp-filters / .opp-filters-overlay in
          styles.css). The overlay only renders visibly under that same
          breakpoint but stays in the DOM either way so its click-outside-
          to-close handler is always available. */}
      {showFilters && (
        <>
          <div className="opp-filters-overlay" onClick={() => setShowFilters(false)} aria-hidden="true" />
          <div className="opp-filters" id="opp-filters-panel" ref={filtersPanelRef} aria-label="Filter opportunities">
          <div className="opp-filters-mobile-header">
            <span className="opp-filters-mobile-title">Filters</span>
            <button
              type="button"
              className="opp-filters-mobile-close"
              onClick={() => setShowFilters(false)}
              aria-label="Close filters"
            >
              <X size={18} weight="bold" />
            </button>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Agency
              {selectedAgencies.size > 0 && <span className="opp-filter-label-count">{selectedAgencies.size}</span>}
            </span>
            <div className="opp-chip-row">
              {agencies.map((a) => (
                <FilterChip key={a} label={a} active={selectedAgencies.has(a)} count={agencyCounts.get(a) || 0}
                  onClick={() => toggleFilter(setSelectedAgencies, a)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Region
              {selectedRegions.size > 0 && <span className="opp-filter-label-count">{selectedRegions.size}</span>}
            </span>
            <div className="opp-chip-row">
              {REGIONS.map((r) => (
                <FilterChip key={r} label={r} active={selectedRegions.has(r)} count={regionCounts.get(r) || 0}
                  onClick={() => toggleFilter(setSelectedRegions, r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label" title="Approximate — based on region, not exact coordinates">
              Geography
            </span>
            <div className="opp-chip-row">
              <FilterChip
                label="10/40 Window"
                active={show1040Only}
                count={window1040Count}
                onClick={() => setShow1040Only((v) => !v)}
              />
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Role type
              {selectedRoles.size > 0 && <span className="opp-filter-label-count">{selectedRoles.size}</span>}
            </span>
            <div className="opp-chip-row">
              {ROLE_TYPES.map((r) => (
                <FilterChip key={r} label={r} active={selectedRoles.has(r)} count={roleCounts.get(r) || 0}
                  onClick={() => toggleFilter(setSelectedRoles, r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Term length
              {selectedTerms.size > 0 && <span className="opp-filter-label-count">{selectedTerms.size}</span>}
            </span>
            <div className="opp-chip-row">
              {TERM_LENGTHS.map((t) => (
                <FilterChip key={t} label={t} active={selectedTerms.has(t)} count={termCounts.get(t) || 0}
                  onClick={() => toggleFilter(setSelectedTerms, t)} />
              ))}
            </div>
          </div>
          {hasActiveFilters && (
            <button type="button" className="opp-clear-filters" onClick={clearFilters}>
              Clear all filters {activeFilterCount > 0 && `(${activeFilterCount})`}
            </button>
          )}
          </div>
        </>
      )}

      {/* Results */}
      {opportunities === null ? (
        fallbackError ? (
          <div className="opp-error" role="alert">
            <p>Couldn't load opportunities right now — try refreshing the page.</p>
          </div>
        ) : (
          <div className="opp-loading" role="status">
            <p className="visually-hidden">Loading opportunities…</p>
            {/* Matches PAGE_SIZE, not an arbitrary smaller count — a real
                page of results is 24 cards, and skeleton/real height
                parity is what keeps the footer from jumping down once
                the swap happens (measured via Lighthouse CLS). */}
            <div className="opp-grid" aria-hidden="true">
              {Array.from({ length: PAGE_SIZE }).map((_, i) => (
                <div className="opp-card-skeleton" key={i} />
              ))}
            </div>
          </div>
        )
      ) : (
        <>
          {loadError && (
            <p className="opp-error opp-error--inline" role="status">
              Couldn't reach live listings right now — showing a recent saved snapshot instead.
            </p>
          )}
          <div className="opp-results-header">
            {/* aria-live so a search/filter change is announced to screen-
                reader users — content still isn't spoken on first mount
                since browsers only announce mutations to an existing live
                region, not its initial render. */}
            <p className="opp-results-count" aria-live="polite">
              {filtered.length.toLocaleString()} {filtered.length === 1 ? 'opportunity' : 'opportunities'}
              {hasActiveFilters ? ' matching your filters' : ''}
              {loading ? ' (refreshing…)' : ''}
            </p>
          </div>

          {filtered.length === 0 ? (
            <div className="opp-empty" role="status">
              <p>
                {activeFilterChips.length > 0
                  ? `No opportunities match ${activeFilterChips.map((c) => c.label).join(', ')}.`
                  : 'No opportunities match your current filters.'}
              </p>
              {hasActiveFilters && (
                <button type="button" className="cta-button" onClick={clearFilters}>
                  Clear filters
                </button>
              )}
            </div>
          ) : (
            <>
              <div className="opp-grid">
                {pageItems.map((opp) => (
                  <OpportunityCard
                    key={opp.id}
                    opp={opp}
                    saved={savedIds.has(opp.id)}
                    onToggleSave={toggleSave}
                    onInquire={openInquiry}
                  />
                ))}
              </div>

              {totalPages > 1 && (
                <nav className="opp-pagination" aria-label="Opportunities pages">
                  <button
                    type="button"
                    className="opp-page-btn"
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                    disabled={page <= 1}
                  >
                    <CaretLeft size={16} weight="bold" /> Previous
                  </button>
                  <span className="opp-page-status">
                    Page {page} of {totalPages}
                  </span>
                  <button
                    type="button"
                    className="opp-page-btn"
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                    disabled={page >= totalPages}
                  >
                    Next <CaretRight size={16} weight="bold" />
                  </button>
                </nav>
              )}
            </>
          )}
        </>
      )}

      <InquiryModal opportunity={inquiryOpp} onClose={() => setInquiryOpp(null)} />
    </div>
  );
}
