// AUTO-GENERATED by scripts/generate-component.js — do not edit by hand.
// Re-run: npm run generate-component
//
// Design tokens applied (from src/styles/tokens.css):
//   --ink-navy: #16233b
//   --atlas-paper: #faf7f0
//   --voyage-teal: #2b6e76
//   --status-unreached: #b5482f
//   --status-formative: #d9a441
//   --status-reached: #4c8a5e
//   --line: rgba(22, 35, 59, 0.15)
//   --muted-text: rgba(22, 35, 59, 0.65)
//   --font-display: 'Fraunces Variable', Georgia, serif
//   --font-body: 'Inter Variable', system-ui, sans-serif
//   --font-mono: 'IBM Plex Mono', 'SFMono-Regular', monospace
//   --space-1: 4px
//   --space-2: 8px
//   --space-3: 12px
//   --space-4: 16px
//   --space-6: 24px
//   --space-8: 32px
//   --space-12: 48px
//   --space-16: 64px
//   --radius: 8px
//   --shadow: 0 2px 12px rgba(22, 35, 59, 0.12)
//   --glass-blur: blur(16px) saturate(1.5)
//   --glass-light-bg: rgba(255, 255, 255, 0.45)
//   --glass-light-border: rgba(255, 255, 255, 0.7)
//   --glass-light-sheen: inset 0 1px 0 rgba(255, 255, 255, 0.85)
//   --glass-dark-bg: rgba(250, 247, 240, 0.06)
//   --glass-dark-border: rgba(250, 247, 240, 0.16)
//   --glass-dark-sheen: inset 0 1px 0 rgba(250, 247, 240, 0.14)
//   --glass-shadow: 0 8px 32px rgba(22, 35, 59, 0.18)
//   --focus-ring: 0 0 0 2px var(--atlas-paper), 0 0 0 4px var(--voyage-teal)
//
// Generated: "2026-07-16T14:24:26.017Z"
// Opportunities: 1440 across 22 agencies

import React, { useState, useEffect, useMemo } from 'react';
import { MagnifyingGlass, Funnel, Heart, EnvelopeSimple, MapPin, Briefcase, Clock, X, CaretDown, SortAscending } from '@phosphor-icons/react';
import { supabase } from '../supabaseClient.js';
import RevealOnScroll from './RevealOnScroll.jsx';

// Reuses the quiz's own scoring output (src/data/scoreAgency.js via
// MatchQuiz.jsx) rather than a second scoring system — CLAUDE.md is explicit
// that getMatches is the one source of "relevance to your quiz" ranking.
const QUIZ_RESULT_KEY = 'fielded_quiz_result';

function loadQuizAgencyScores() {
  try {
    const raw = localStorage.getItem(QUIZ_RESULT_KEY);
    if (!raw) return null;
    const saved = JSON.parse(raw);
    if (!saved || !Array.isArray(saved.matches) || saved.matches.length === 0) return null;
    return new Map(saved.matches.map((m) => [m.name, m.score]));
  } catch {
    return null;
  }
}

const SORT_RELEVANCE = 'relevance';
const SORT_AGENCY = 'agency';
const SORT_RECENT = 'recent';

// The full opportunities list used to be inlined here as a literal — with
// 1500+ records that made this one file (and its route chunk) ~650KB before
// gzip, dwarfing every other route. It's now a static JSON asset fetched at
// runtime instead, matching the pattern already used for the world map's
// people-groups data (see WorldMap.jsx) — same-origin, CDN-cached, and still
// resilient to Supabase specifically being unreachable, which is what this
// fallback is actually for.
//
// The static snapshot is the primary data source on every load (one 568KB
// CDN-cached fetch). Supabase is only consulted as an optional background
// freshness check, gated by VITE_ENABLE_FRESH_FETCH — every visit used to
// fire two sequential 1000-row Supabase queries on top of the static fetch,
// which is 1,500+ rows downloaded for data the static snapshot already had.
const FALLBACK_URL = '/data/opportunities-fallback.json';
const ENABLE_FRESH_FETCH = import.meta.env.VITE_ENABLE_FRESH_FETCH === 'true';

const REGIONS = [
  "Central Asia",
  "East Asia",
  "Europe",
  "Islands / Oceania",
  "Latin America",
  "Middle East / North Africa",
  "North America",
  "Oceania",
  "Oceania / Asia-Pacific",
  "South Asia",
  "Southeast Asia",
  "Sub-Saharan Africa"
];
const ROLE_TYPES = [
  "Bible translation/linguistics",
  "administration",
  "aviation/logistics",
  "business as mission",
  "children/youth ministry",
  "church planting",
  "construction/maintenance",
  "deaf ministry",
  "discipleship training",
  "education/TESOL",
  "evangelism/discipleship",
  "internship",
  "media/creative",
  "medical",
  "member care",
  "mobilization",
  "prayer",
  "relief and development",
  "research",
  "short-term missions",
  "sports ministry",
  "technology",
  "theological education",
  "training/leadership",
  "volunteer"
];
const TERM_LENGTHS = [
  "short-term (under 2 years)",
  "mid-term (2-4 years)",
  "career/long-term"
];

function FilterChip({ label, active, count, onClick }) {
  return (
    <button
      type="button"
      className={`opp-filter-chip${active ? ' opp-filter-chip--active' : ''}`}
      onClick={onClick}
    >
      {label}
      {count > 0 && <span className="opp-filter-chip-count">{count}</span>}
    </button>
  );
}

function OpportunityCard({ opp, saved, onToggleSave, onInquire }) {
  return (
    <RevealOnScroll className="opp-card-wrapper">
      <article className="opp-card">
        <div className="opp-card-header">
          <span className="opp-card-agency">{opp.agency}</span>
          <div className="opp-card-actions">
            <button
              type="button"
              className={`opp-icon-btn${saved ? ' opp-icon-btn--saved' : ''}`}
              onClick={() => onToggleSave(opp.id)}
              aria-label={saved ? 'Remove from saved' : 'Save opportunity'}
            >
              <Heart weight={saved ? 'fill' : 'regular'} size={18} />
            </button>
          </div>
        </div>

        <h3 className="opp-card-title">{opp.title}</h3>

        {opp.description && (
          <p className="opp-card-desc">{opp.description}</p>
        )}

        <div className="opp-card-meta">
          {opp.location && (
            <span className="opp-card-tag">
              <MapPin size={14} weight="bold" /> {opp.location}
            </span>
          )}
          {opp.role_type && (
            <span className="opp-card-tag">
              <Briefcase size={14} weight="bold" /> {opp.role_type}
            </span>
          )}
          {opp.term_length && (
            <span className="opp-card-tag">
              <Clock size={14} weight="bold" /> {opp.term_length}
            </span>
          )}
        </div>

        <div className="opp-card-footer">
          <a href={opp.url} target="_blank" rel="noreferrer" className="opp-card-link">
            View details &rarr;
          </a>
          <button
            type="button"
            className="opp-inquire-btn"
            onClick={() => onInquire(opp)}
          >
            <EnvelopeSimple size={16} weight="bold" /> Inquire
          </button>
        </div>
      </article>
    </RevealOnScroll>
  );
}

function InquiryModal({ opportunity, onClose }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);

  if (!opportunity) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (supabase) {
      await supabase.from('inquiries').insert({
        opportunity_id: opportunity.id,
        name,
        email,
        message,
        agency: opportunity.agency,
        opportunity_title: opportunity.title
      });
    }
    setSent(true);
  };

  return (
    <div className="opp-modal-overlay" role="presentation" onClick={onClose} onKeyDown={(e) => { if (e.key === 'Escape') onClose(); }}>
      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */}
      <div className="opp-modal" role="dialog" aria-label="Send inquiry" onClick={(e) => e.stopPropagation()}>
        <button type="button" className="opp-modal-close" onClick={onClose} aria-label="Close">
          <X size={20} />
        </button>

        {sent ? (
          <div className="opp-modal-success">
            <h3>Inquiry sent</h3>
            <p>Your interest in <strong>{opportunity.title}</strong> at {opportunity.agency} has been noted. Check your email for next steps.</p>
            <button type="button" className="cta-button" onClick={onClose}>Close</button>
          </div>
        ) : (
          <>
            <h3>Inquire about this opportunity</h3>
            <p className="opp-modal-subtitle">
              <strong>{opportunity.title}</strong> &mdash; {opportunity.agency}
            </p>
            <form onSubmit={handleSubmit} className="opp-inquiry-form">
              <label>
                Name
                <input type="text" value={name} onChange={(e) => setName(e.target.value)} required />
              </label>
              <label>
                Email
                <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </label>
              <label>
                Message
                <textarea
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Tell them a bit about yourself and why this opportunity interests you..."
                />
              </label>
              <button type="submit" className="cta-button">Send inquiry</button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}

export default function OpportunitiesExplorer({ agencyFilter }) {
  // null = not loaded yet (distinct from "loaded, zero results" so the
  // empty-filters copy doesn't flash for a normal loading heartbeat).
  const [opportunities, setOpportunities] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState(false);
  const [fallbackError, setFallbackError] = useState(false);

  // Filters — Sets for multi-select (union/OR within a category, intersection/AND across categories)
  const [search, setSearch] = useState('');
  const [selectedAgencies, setSelectedAgencies] = useState(() =>
    agencyFilter ? new Set([agencyFilter]) : new Set()
  );
  const [selectedRegions, setSelectedRegions] = useState(new Set());
  const [selectedRoles, setSelectedRoles] = useState(new Set());
  const [selectedTerms, setSelectedTerms] = useState(new Set());
  const [showFilters, setShowFilters] = useState(false);

  const [quizScores] = useState(loadQuizAgencyScores);
  const [sortMode, setSortMode] = useState(() => (quizScores ? SORT_RELEVANCE : SORT_RECENT));

  function toggleFilter(setter, value) {
    setter(prev => {
      const next = new Set(prev);
      if (next.has(value)) next.delete(value);
      else next.add(value);
      return next;
    });
  }

  // Saved + inquiry
  const [savedIds, setSavedIds] = useState(() => {
    try {
      return new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
    } catch { return new Set(); }
  });
  const [showSavedOnly, setShowSavedOnly] = useState(false);
  const [inquiryOpp, setInquiryOpp] = useState(null);

  // Loads the static fallback snapshot once on mount. Only applies it if
  // nothing has been set yet — if the live Supabase fetch below already won
  // the race, this must never clobber fresher data with the stale snapshot.
  useEffect(() => {
    let cancelled = false;
    fetch(FALLBACK_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        setOpportunities((prev) => (prev === null ? data : prev));
      })
      .catch((err) => {
        if (cancelled) return;
        console.error('Failed to load the opportunities fallback snapshot:', err);
        setFallbackError(true);
      });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    if (!supabase || !ENABLE_FRESH_FETCH) return;
    let cancelled = false;
    async function refresh() {
      setLoading(true);
      setLoadError(false);
      const allRows = [];
      const PAGE_SIZE = 1000;
      let from = 0;
      try {
        while (true) {
          const { data, error } = await supabase
            .from('opportunities')
            .select('id, agency, title, url, location, region, role_type, term_length, description')
            .eq('active', true)
            .order('agency', { ascending: true })
            .order('title', { ascending: true })
            .range(from, from + PAGE_SIZE - 1);
          if (cancelled) return;
          if (error) throw error;
          allRows.push(...(data || []));
          if (!data || data.length < PAGE_SIZE) break;
          from += PAGE_SIZE;
        }
        if (!cancelled && allRows.length > 0) {
          setOpportunities(allRows);
        }
      } catch (err) {
        if (cancelled) return;
        // Network hiccup or RLS misconfig — leave whatever the fallback
        // effect already loaded (or will load) in place rather than an
        // empty list, but surface it so a stale-data banner can render and
        // so this shows up in error monitoring instead of failing silently.
        console.error('Failed to load live opportunities, showing cached snapshot:', err);
        setLoadError(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    refresh();
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    localStorage.setItem('fielded_saved_opps', JSON.stringify([...savedIds]));
  }, [savedIds]);

  const agencies = useMemo(
    () => [...new Set((opportunities || []).map((o) => o.agency))].sort(),
    [opportunities]
  );

  const filtered = useMemo(() => {
    let list = opportunities || [];

    if (showSavedOnly) {
      list = list.filter((o) => savedIds.has(o.id));
    }
    if (search) {
      const q = search.toLowerCase();
      list = list.filter((o) =>
        o.title.toLowerCase().includes(q) ||
        (o.description || '').toLowerCase().includes(q) ||
        o.agency.toLowerCase().includes(q) ||
        (o.location || '').toLowerCase().includes(q)
      );
    }
    if (selectedAgencies.size > 0) list = list.filter((o) => selectedAgencies.has(o.agency));
    if (selectedRegions.size > 0) list = list.filter((o) => selectedRegions.has(o.region));
    if (selectedRoles.size > 0) list = list.filter((o) => selectedRoles.has(o.role_type));
    if (selectedTerms.size > 0) list = list.filter((o) => selectedTerms.has(o.term_length));

    if (sortMode === SORT_AGENCY) {
      list = [...list].sort((a, b) => a.agency.localeCompare(b.agency) || a.title.localeCompare(b.title));
    } else if (sortMode === SORT_RELEVANCE && quizScores) {
      list = [...list].sort((a, b) => (quizScores.get(b.agency) ?? -1) - (quizScores.get(a.agency) ?? -1));
    }
    // SORT_RECENT: no reorder — the static snapshot's own order is the closest
    // thing to "recently added" available without a source created_at field.

    return list;
  }, [opportunities, search, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, showSavedOnly, savedIds, sortMode, quizScores]);

  function toggleSave(id) {
    setSavedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function clearFilters() {
    setSearch('');
    setSelectedAgencies(new Set());
    setSelectedRegions(new Set());
    setSelectedRoles(new Set());
    setSelectedTerms(new Set());
    setShowSavedOnly(false);
  }

  const activeFilterCount = selectedAgencies.size + selectedRegions.size + selectedRoles.size + selectedTerms.size;
  const hasActiveFilters = search || activeFilterCount > 0 || showSavedOnly;

  return (
    <div className="opp-explorer">
      {/* Search + filter bar */}
      <div className="opp-toolbar">
        <div className="opp-search-wrap">
          <MagnifyingGlass size={18} className="opp-search-icon" />
          <input
            type="search"
            className="opp-search"
            placeholder="Search opportunities..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <button
          type="button"
          className={`opp-filter-toggle${showFilters ? ' opp-filter-toggle--open' : ''}`}
          onClick={() => setShowFilters(!showFilters)}
        >
          <Funnel size={16} weight="bold" />
          Filters
          {activeFilterCount > 0 && <span className="opp-filter-badge">{activeFilterCount}</span>}
          <CaretDown size={14} className={`opp-caret${showFilters ? ' opp-caret--open' : ''}`} />
        </button>
        <button
          type="button"
          className={`opp-icon-btn opp-saved-toggle${showSavedOnly ? ' opp-icon-btn--saved' : ''}`}
          onClick={() => setShowSavedOnly(!showSavedOnly)}
          aria-label={showSavedOnly ? 'Show all' : 'Show saved only'}
        >
          <Heart weight={showSavedOnly ? 'fill' : 'regular'} size={18} />
          <span className="opp-saved-count">{savedIds.size}</span>
        </button>
        <label className="opp-sort">
          <SortAscending size={16} weight="bold" />
          <span className="visually-hidden">Sort opportunities by</span>
          <select
            className="opp-sort-select"
            value={sortMode}
            onChange={(e) => setSortMode(e.target.value)}
          >
            {quizScores && <option value={SORT_RELEVANCE}>Relevance</option>}
            <option value={SORT_AGENCY}>Agency A–Z</option>
            <option value={SORT_RECENT}>Recently added</option>
          </select>
        </label>
      </div>

      {sortMode === SORT_RELEVANCE && quizScores && (
        <p className="opp-sort-pill">Sorted by your quiz matches</p>
      )}

      {/* Expandable filter panel */}
      {showFilters && (
        <div className="opp-filters">
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Agency
              {selectedAgencies.size > 0 && <span className="opp-filter-label-count">{selectedAgencies.size}</span>}
            </span>
            <div className="opp-chip-row">
              {agencies.map((a) => (
                <FilterChip key={a} label={a} active={selectedAgencies.has(a)}
                  onClick={() => toggleFilter(setSelectedAgencies, a)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Region
              {selectedRegions.size > 0 && <span className="opp-filter-label-count">{selectedRegions.size}</span>}
            </span>
            <div className="opp-chip-row">
              {REGIONS.map((r) => (
                <FilterChip key={r} label={r} active={selectedRegions.has(r)}
                  onClick={() => toggleFilter(setSelectedRegions, r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Role type
              {selectedRoles.size > 0 && <span className="opp-filter-label-count">{selectedRoles.size}</span>}
            </span>
            <div className="opp-chip-row">
              {ROLE_TYPES.map((r) => (
                <FilterChip key={r} label={r} active={selectedRoles.has(r)}
                  onClick={() => toggleFilter(setSelectedRoles, r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Term length
              {selectedTerms.size > 0 && <span className="opp-filter-label-count">{selectedTerms.size}</span>}
            </span>
            <div className="opp-chip-row">
              {TERM_LENGTHS.map((t) => (
                <FilterChip key={t} label={t} active={selectedTerms.has(t)}
                  onClick={() => toggleFilter(setSelectedTerms, t)} />
              ))}
            </div>
          </div>
          {hasActiveFilters && (
            <button type="button" className="opp-clear-filters" onClick={clearFilters}>
              Clear all filters {activeFilterCount > 0 && `(${activeFilterCount})`}
            </button>
          )}
        </div>
      )}

      {/* Results */}
      {opportunities === null ? (
        fallbackError ? (
          <div className="opp-error" role="alert">
            <p>Couldn't load opportunities right now — try refreshing the page.</p>
          </div>
        ) : (
          <div className="opp-loading" role="status">
            <p>Loading opportunities…</p>
          </div>
        )
      ) : (
        <>
          {loadError && (
            <p className="opp-error opp-error--inline" role="status">
              Couldn't reach live listings right now — showing a recent saved snapshot instead.
            </p>
          )}
          <div className="opp-results-header">
            <p className="opp-results-count">
              {filtered.length} {filtered.length === 1 ? 'opportunity' : 'opportunities'}
              {hasActiveFilters ? ' matching your filters' : ''}
              {loading ? ' (refreshing…)' : ''}
            </p>
          </div>

          {filtered.length === 0 ? (
            <div className="opp-empty">
              <p>No opportunities match your current filters.</p>
              {hasActiveFilters && (
                <button type="button" className="cta-button" onClick={clearFilters}>
                  Clear filters
                </button>
              )}
            </div>
          ) : (
            <div className="opp-grid">
              {filtered.map((opp) => (
                <OpportunityCard
                  key={opp.id}
                  opp={opp}
                  saved={savedIds.has(opp.id)}
                  onToggleSave={toggleSave}
                  onInquire={setInquiryOpp}
                />
              ))}
            </div>
          )}
        </>
      )}

      <InquiryModal opportunity={inquiryOpp} onClose={() => setInquiryOpp(null)} />
    </div>
  );
}
