// AUTO-GENERATED by scripts/generate-component.js — do not edit by hand.
// Re-run: npm run generate-component
//
// Design tokens applied (from src/styles/tokens.css):
/* __TOKEN_COMMENT__ */
//
// Generated: '__GENERATED_DATE__'
// Opportunities: '__OPP_COUNT__' across '__AGENCY_COUNT__' agencies

import React, { useState, useEffect, useMemo } from 'react';
import { MagnifyingGlass, Funnel, Heart, EnvelopeSimple, MapPin, Briefcase, Clock, X, CaretDown } from '@phosphor-icons/react';
import { supabase } from '../supabaseClient.js';
import RevealOnScroll from './RevealOnScroll.jsx';

const BAKED_OPPORTUNITIES = '__BAKED_OPPORTUNITIES__';

const REGIONS = '__REGIONS__';
const ROLE_TYPES = '__ROLE_TYPES__';
const TERM_LENGTHS = '__TERM_LENGTHS__';

function FilterChip({ label, active, onClick }) {
  return (
    <button
      type="button"
      className={`opp-filter-chip${active ? ' opp-filter-chip--active' : ''}`}
      onClick={onClick}
    >
      {label}
    </button>
  );
}

function OpportunityCard({ opp, saved, onToggleSave, onInquire }) {
  return (
    <RevealOnScroll className="opp-card-wrapper">
      <article className="opp-card">
        <div className="opp-card-header">
          <span className="opp-card-agency">{opp.agency}</span>
          <div className="opp-card-actions">
            <button
              type="button"
              className={`opp-icon-btn${saved ? ' opp-icon-btn--saved' : ''}`}
              onClick={() => onToggleSave(opp.id)}
              aria-label={saved ? 'Remove from saved' : 'Save opportunity'}
            >
              <Heart weight={saved ? 'fill' : 'regular'} size={18} />
            </button>
          </div>
        </div>

        <h3 className="opp-card-title">{opp.title}</h3>

        {opp.description && (
          <p className="opp-card-desc">{opp.description}</p>
        )}

        <div className="opp-card-meta">
          {opp.location && (
            <span className="opp-card-tag">
              <MapPin size={14} weight="bold" /> {opp.location}
            </span>
          )}
          {opp.role_type && (
            <span className="opp-card-tag">
              <Briefcase size={14} weight="bold" /> {opp.role_type}
            </span>
          )}
          {opp.term_length && (
            <span className="opp-card-tag">
              <Clock size={14} weight="bold" /> {opp.term_length}
            </span>
          )}
        </div>

        <div className="opp-card-footer">
          <a href={opp.url} target="_blank" rel="noreferrer" className="opp-card-link">
            View details &rarr;
          </a>
          <button
            type="button"
            className="opp-inquire-btn"
            onClick={() => onInquire(opp)}
          >
            <EnvelopeSimple size={16} weight="bold" /> Inquire
          </button>
        </div>
      </article>
    </RevealOnScroll>
  );
}

function InquiryModal({ opportunity, onClose }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);

  if (!opportunity) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (supabase) {
      await supabase.from('inquiries').insert({
        opportunity_id: opportunity.id,
        name,
        email,
        message,
        agency: opportunity.agency,
        opportunity_title: opportunity.title
      });
    }
    setSent(true);
  };

  return (
    <div className="opp-modal-overlay" role="presentation" onClick={onClose} onKeyDown={(e) => { if (e.key === 'Escape') onClose(); }}>
      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */}
      <div className="opp-modal" role="dialog" aria-label="Send inquiry" onClick={(e) => e.stopPropagation()}>
        <button type="button" className="opp-modal-close" onClick={onClose} aria-label="Close">
          <X size={20} />
        </button>

        {sent ? (
          <div className="opp-modal-success">
            <h3>Inquiry sent</h3>
            <p>Your interest in <strong>{opportunity.title}</strong> at {opportunity.agency} has been noted. Check your email for next steps.</p>
            <button type="button" className="cta-button" onClick={onClose}>Close</button>
          </div>
        ) : (
          <>
            <h3>Inquire about this opportunity</h3>
            <p className="opp-modal-subtitle">
              <strong>{opportunity.title}</strong> &mdash; {opportunity.agency}
            </p>
            <form onSubmit={handleSubmit} className="opp-inquiry-form">
              <label>
                Name
                <input type="text" value={name} onChange={(e) => setName(e.target.value)} required />
              </label>
              <label>
                Email
                <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </label>
              <label>
                Message
                <textarea
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Tell them a bit about yourself and why this opportunity interests you..."
                />
              </label>
              <button type="submit" className="cta-button">Send inquiry</button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}

export default function OpportunitiesExplorer({ agencyFilter }) {
  const [opportunities, setOpportunities] = useState(BAKED_OPPORTUNITIES);
  const [loading, setLoading] = useState(false);

  // Filters
  const [search, setSearch] = useState('');
  const [selectedAgency, setSelectedAgency] = useState(agencyFilter || '');
  const [selectedRegion, setSelectedRegion] = useState('');
  const [selectedRole, setSelectedRole] = useState('');
  const [selectedTerm, setSelectedTerm] = useState('');
  const [showFilters, setShowFilters] = useState(false);

  // Saved + inquiry
  const [savedIds, setSavedIds] = useState(() => {
    try {
      return new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
    } catch { return new Set(); }
  });
  const [showSavedOnly, setShowSavedOnly] = useState(false);
  const [inquiryOpp, setInquiryOpp] = useState(null);

  useEffect(() => {
    if (!supabase) return;
    let cancelled = false;
    async function refresh() {
      setLoading(true);
      const { data } = await supabase
        .from('opportunities')
        .select('id, agency, title, url, location, region, role_type, term_length, description')
        .eq('active', true)
        .order('agency', { ascending: true })
        .order('title', { ascending: true });
      if (!cancelled && data && data.length > 0) {
        setOpportunities(data);
      }
      setLoading(false);
    }
    refresh();
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    localStorage.setItem('fielded_saved_opps', JSON.stringify([...savedIds]));
  }, [savedIds]);

  const agencies = useMemo(
    () => [...new Set(opportunities.map((o) => o.agency))].sort(),
    [opportunities]
  );

  const filtered = useMemo(() => {
    let list = opportunities;

    if (showSavedOnly) {
      list = list.filter((o) => savedIds.has(o.id));
    }
    if (search) {
      const q = search.toLowerCase();
      list = list.filter((o) =>
        o.title.toLowerCase().includes(q) ||
        (o.description || '').toLowerCase().includes(q) ||
        o.agency.toLowerCase().includes(q) ||
        (o.location || '').toLowerCase().includes(q)
      );
    }
    if (selectedAgency) list = list.filter((o) => o.agency === selectedAgency);
    if (selectedRegion) list = list.filter((o) => o.region === selectedRegion);
    if (selectedRole) list = list.filter((o) => o.role_type === selectedRole);
    if (selectedTerm) list = list.filter((o) => o.term_length === selectedTerm);

    return list;
  }, [opportunities, search, selectedAgency, selectedRegion, selectedRole, selectedTerm, showSavedOnly, savedIds]);

  function toggleSave(id) {
    setSavedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function clearFilters() {
    setSearch('');
    setSelectedAgency('');
    setSelectedRegion('');
    setSelectedRole('');
    setSelectedTerm('');
    setShowSavedOnly(false);
  }

  const hasActiveFilters = search || selectedAgency || selectedRegion || selectedRole || selectedTerm || showSavedOnly;

  return (
    <div className="opp-explorer">
      {/* Search + filter bar */}
      <div className="opp-toolbar">
        <div className="opp-search-wrap">
          <MagnifyingGlass size={18} className="opp-search-icon" />
          <input
            type="search"
            className="opp-search"
            placeholder="Search opportunities..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <button
          type="button"
          className={`opp-filter-toggle${showFilters ? ' opp-filter-toggle--open' : ''}`}
          onClick={() => setShowFilters(!showFilters)}
        >
          <Funnel size={16} weight="bold" />
          Filters
          {hasActiveFilters && <span className="opp-filter-badge" />}
          <CaretDown size={14} className={`opp-caret${showFilters ? ' opp-caret--open' : ''}`} />
        </button>
        <button
          type="button"
          className={`opp-icon-btn opp-saved-toggle${showSavedOnly ? ' opp-icon-btn--saved' : ''}`}
          onClick={() => setShowSavedOnly(!showSavedOnly)}
          aria-label={showSavedOnly ? 'Show all' : 'Show saved only'}
        >
          <Heart weight={showSavedOnly ? 'fill' : 'regular'} size={18} />
          <span className="opp-saved-count">{savedIds.size}</span>
        </button>
      </div>

      {/* Expandable filter panel */}
      {showFilters && (
        <div className="opp-filters">
          <div className="opp-filter-group">
            <span className="opp-filter-label">Agency</span>
            <select value={selectedAgency} onChange={(e) => setSelectedAgency(e.target.value)}>
              <option value="">All agencies</option>
              {agencies.map((a) => <option key={a} value={a}>{a}</option>)}
            </select>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">Region</span>
            <div className="opp-chip-row">
              {REGIONS.map((r) => (
                <FilterChip key={r} label={r} active={selectedRegion === r}
                  onClick={() => setSelectedRegion(selectedRegion === r ? '' : r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">Role type</span>
            <div className="opp-chip-row">
              {ROLE_TYPES.map((r) => (
                <FilterChip key={r} label={r} active={selectedRole === r}
                  onClick={() => setSelectedRole(selectedRole === r ? '' : r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">Term length</span>
            <div className="opp-chip-row">
              {TERM_LENGTHS.map((t) => (
                <FilterChip key={t} label={t} active={selectedTerm === t}
                  onClick={() => setSelectedTerm(selectedTerm === t ? '' : t)} />
              ))}
            </div>
          </div>
          {hasActiveFilters && (
            <button type="button" className="opp-clear-filters" onClick={clearFilters}>
              Clear all filters
            </button>
          )}
        </div>
      )}

      {/* Results */}
      <div className="opp-results-header">
        <p className="opp-results-count">
          {filtered.length} {filtered.length === 1 ? 'opportunity' : 'opportunities'}
          {hasActiveFilters ? ' matching your filters' : ''}
          {loading ? ' (refreshing…)' : ''}
        </p>
      </div>

      {filtered.length === 0 ? (
        <div className="opp-empty">
          <p>No opportunities match your current filters.</p>
          {hasActiveFilters && (
            <button type="button" className="cta-button" onClick={clearFilters}>
              Clear filters
            </button>
          )}
        </div>
      ) : (
        <div className="opp-grid">
          {filtered.map((opp) => (
            <OpportunityCard
              key={opp.id}
              opp={opp}
              saved={savedIds.has(opp.id)}
              onToggleSave={toggleSave}
              onInquire={setInquiryOpp}
            />
          ))}
        </div>
      )}

      <InquiryModal opportunity={inquiryOpp} onClose={() => setInquiryOpp(null)} />
    </div>
  );
}
