// AUTO-GENERATED by scripts/generate-component.js — do not edit by hand.
// Re-run: npm run generate-component
//
// Design tokens applied (from src/styles/tokens.css):
/* __TOKEN_COMMENT__ */
//
// Generated: '__GENERATED_DATE__'
// Opportunities: '__OPP_COUNT__' across '__AGENCY_COUNT__' agencies

import React, { useState, useEffect, useMemo, useRef } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { MagnifyingGlass, Funnel, Heart, EnvelopeSimple, MapPin, Briefcase, Clock, X, CaretDown, SortAscending, CaretLeft, CaretRight } from '@phosphor-icons/react';
import { supabase } from '../supabaseClient.js';
import RevealOnScroll from './RevealOnScroll.jsx';

// Reuses the quiz's own scoring output (src/data/scoreAgency.js via
// MatchQuiz.jsx) rather than a second scoring system — CLAUDE.md is explicit
// that getMatches is the one source of "relevance to your quiz" ranking.
const QUIZ_RESULT_KEY = 'fielded_quiz_result';

function loadQuizAgencyScores() {
  try {
    const raw = localStorage.getItem(QUIZ_RESULT_KEY);
    if (!raw) return null;
    const saved = JSON.parse(raw);
    if (!saved || !Array.isArray(saved.matches) || saved.matches.length === 0) return null;
    return new Map(saved.matches.map((m) => [m.name, m.score]));
  } catch {
    return null;
  }
}

const SORT_RELEVANCE = 'relevance';
const SORT_AGENCY = 'agency';
// Neither `scraped_at` nor `date_posted` is a reliable per-listing freshness
// signal (scraped_at is a bulk re-scrape timestamp, date_posted is almost
// always null) — a round-robin interleave by agency is the honest default
// instead of a fabricated "recently added" claim. It also fixes the actual
// bug: raw alphabetical-by-agency reads as an ABWE directory since ABWE
// alone accounts for the first ~250 rows.
const SORT_MIXED = 'mixed';

const PAGE_SIZE = 24;

// One item from each agency bucket per round, cycling until every bucket is
// exhausted — turns "first 250 rows are all ABWE" into "one ABWE listing
// every ~22 opportunities." Bucket order follows first-appearance order in
// `list` (which is itself agency-alphabetical from the source query), so the
// interleave is still deterministic and stable across renders.
function interleaveByAgency(list) {
  const buckets = new Map();
  for (const o of list) {
    if (!buckets.has(o.agency)) buckets.set(o.agency, []);
    buckets.get(o.agency).push(o);
  }
  const bucketArrays = [...buckets.values()];
  const result = [];
  let i = 0;
  while (result.length < list.length) {
    for (const bucket of bucketArrays) {
      if (i < bucket.length) result.push(bucket[i]);
    }
    i += 1;
  }
  return result;
}

// Parses a comma-separated query-param value into a Set, or an empty Set if
// the param is absent — used for every multi-select filter's URL sync.
function parseSetParam(params, key) {
  const raw = params.get(key);
  return raw ? new Set(raw.split(',').filter(Boolean)) : new Set();
}

// The full opportunities list used to be inlined here as a literal — with
// 1500+ records that made this one file (and its route chunk) ~650KB before
// gzip, dwarfing every other route. It's now a static JSON asset fetched at
// runtime instead, matching the pattern already used for the world map's
// people-groups data (see WorldMap.jsx) — same-origin, CDN-cached, and still
// resilient to Supabase specifically being unreachable, which is what this
// fallback is actually for.
//
// The static snapshot is the primary data source on every load (one 568KB
// CDN-cached fetch). Supabase is only consulted as an optional background
// freshness check, gated by VITE_ENABLE_FRESH_FETCH — every visit used to
// fire two sequential 1000-row Supabase queries on top of the static fetch,
// which is 1,500+ rows downloaded for data the static snapshot already had.
const FALLBACK_URL = '/data/opportunities-fallback.json';
const ENABLE_FRESH_FETCH = import.meta.env.VITE_ENABLE_FRESH_FETCH === 'true';

const REGIONS = '__REGIONS__';
const ROLE_TYPES = '__ROLE_TYPES__';
const TERM_LENGTHS = '__TERM_LENGTHS__';
const TRADITIONS = '__TRADITIONS__';
const RELIGIONS = '__RELIGIONS__';
const AGENCY_TRADITIONS = '__AGENCY_TRADITIONS__';

// Map regions to common target religions for those areas
const REGION_RELIGIONS = {
  'Sub-Saharan Africa': ['Christian', 'Muslim', 'Animist'],
  'Middle East / North Africa': ['Muslim', 'Christian'],
  'Central Asia': ['Muslim', 'Buddhist', 'Christian'],
  'South Asia': ['Hindu', 'Muslim', 'Buddhist', 'Christian'],
  'Southeast Asia': ['Buddhist', 'Muslim', 'Christian', 'Animist'],
  'East Asia': ['Buddhist', 'Atheist/Secular', 'Christian'],
  'Latin America': ['Christian', 'Animist'],
  'Western Europe': ['Atheist/Secular', 'Christian', 'Muslim'],
  'Eastern Europe': ['Christian', 'Atheist/Secular', 'Muslim'],
  'Balkans': ['Christian', 'Muslim'],
  'Nordic countries': ['Atheist/Secular', 'Christian'],
  'North America': ['Christian', 'Atheist/Secular'],
  'Islands / Oceania': ['Christian', 'Animist'],
  'Oceania / Asia-Pacific': ['Christian', 'Animist'],
};

function getTradition(opportunity) {
  return AGENCY_TRADITIONS[opportunity.agency] || null;
}

function getReligions(opportunity) {
  const region = opportunity.region;
  return region ? REGION_RELIGIONS[region] || [] : [];
}

// "Inquire" needs an object — but agency names are a mix of shapes
// ("ABWE", "Africa Inland Mission (AIM)", "Cru (Campus Crusade for
// Christ)"), so a blind "text in parens" extraction would turn Cru into
// "Inquire with Campus Crusade for Christ." Only treats the parenthetical
// as the short name when it actually looks like an acronym (all caps,
// 2-6 letters) — otherwise falls back to the text before the parens, and
// falls back to the full name when there's no parenthetical at all. Never
// invents an abbreviation that isn't already present in the source name.
function shortAgencyName(agency) {
  const match = agency.match(/^(.*?)\s*\(([^)]+)\)\s*$/);
  if (!match) return agency;
  const [, before, paren] = match;
  return /^[A-Z]{2,6}$/.test(paren) ? paren : before.trim();
}

function FilterChip({ label, active, count, onClick }) {
  return (
    <button
      type="button"
      className={`opp-filter-chip${active ? ' opp-filter-chip--active' : ''}`}
      onClick={onClick}
    >
      <span>{label}</span>
      {count > 0 && <span className="opp-filter-chip-count">({count.toLocaleString()})</span>}
    </button>
  );
}

function OpportunityCard({ opp, saved, onToggleSave, onInquire }) {
  return (
    <RevealOnScroll className="opp-card-wrapper">
      <article className="opp-card">
        <div className="opp-card-header">
          <span className="opp-card-agency">{opp.agency}</span>
          <div className="opp-card-actions">
            <button
              type="button"
              className={`opp-icon-btn${saved ? ' opp-icon-btn--saved' : ''}`}
              onClick={() => onToggleSave(opp.id)}
              aria-label={saved ? 'Remove from saved' : 'Save opportunity'}
            >
              <Heart weight={saved ? 'fill' : 'regular'} size={18} />
            </button>
          </div>
        </div>

        <h2 className="opp-card-title">{opp.title}</h2>

        {opp.description && (
          <p className="opp-card-desc">{opp.description}</p>
        )}

        <div className="opp-card-meta">
          {opp.location && (
            <span className="opp-card-tag">
              <MapPin size={14} weight="bold" /> {opp.location}
            </span>
          )}
          {opp.role_type && (
            <span className="opp-card-tag">
              <Briefcase size={14} weight="bold" /> {opp.role_type}
            </span>
          )}
          {opp.term_length && (
            <span className="opp-card-tag">
              <Clock size={14} weight="bold" /> {opp.term_length}
            </span>
          )}
        </div>

        <div className="opp-card-footer">
          <a href={opp.url} target="_blank" rel="noreferrer" className="opp-card-link">
            View details &rarr;
          </a>
          <button
            type="button"
            className="opp-inquire-btn"
            onClick={() => onInquire(opp)}
          >
            <EnvelopeSimple size={16} weight="bold" /> Inquire with {shortAgencyName(opp.agency)}
          </button>
        </div>
      </article>
    </RevealOnScroll>
  );
}

function InquiryModal({ opportunity, onClose }) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [sent, setSent] = useState(false);

  if (!opportunity) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (supabase) {
      await supabase.from('inquiries').insert({
        opportunity_id: opportunity.id,
        name,
        email,
        message,
        agency: opportunity.agency,
        opportunity_title: opportunity.title
      });
    }
    setSent(true);
  };

  return (
    <div className="opp-modal-overlay" role="presentation" onClick={onClose} onKeyDown={(e) => { if (e.key === 'Escape') onClose(); }}>
      {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions, jsx-a11y/click-events-have-key-events */}
      <div className="opp-modal" role="dialog" aria-label="Send inquiry" onClick={(e) => e.stopPropagation()}>
        <button type="button" className="opp-modal-close" onClick={onClose} aria-label="Close">
          <X size={20} />
        </button>

        {sent ? (
          <div className="opp-modal-success">
            <h3>Inquiry sent</h3>
            <p>Your interest in <strong>{opportunity.title}</strong> at {opportunity.agency} has been noted. Check your email for next steps.</p>
            <button type="button" className="cta-button" onClick={onClose}>Close</button>
          </div>
        ) : (
          <>
            <h3>Inquire about this opportunity</h3>
            <p className="opp-modal-subtitle">
              <strong>{opportunity.title}</strong> &mdash; {opportunity.agency}
            </p>
            <form onSubmit={handleSubmit} className="opp-inquiry-form">
              <label>
                Name
                <input type="text" value={name} onChange={(e) => setName(e.target.value)} required />
              </label>
              <label>
                Email
                <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required />
              </label>
              <label>
                Message
                <textarea
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  rows={4}
                  placeholder="Tell them a bit about yourself and why this opportunity interests you..."
                />
              </label>
              <button type="submit" className="cta-button">Send inquiry</button>
            </form>
          </>
        )}
      </div>
    </div>
  );
}

export default function OpportunitiesExplorer({ agencyFilter }) {
  // null = not loaded yet (distinct from "loaded, zero results" so the
  // empty-filters copy doesn't flash for a normal loading heartbeat).
  const [opportunities, setOpportunities] = useState(null);
  const [loading, setLoading] = useState(false);
  const [loadError, setLoadError] = useState(false);
  const [fallbackError, setFallbackError] = useState(false);

  // Page, filters, and sort all live in the URL (?page=2&agency=ABWE&category=medical)
  // so results are shareable and survive a reload — read once on mount as the
  // initial state, then kept in sync by the effect below on every change.
  const [searchParams, setSearchParams] = useSearchParams();

  // Filters — Sets for multi-select (union/OR within a category, intersection/AND across categories)
  const [search, setSearch] = useState(() => searchParams.get('q') || '');
  const [selectedAgencies, setSelectedAgencies] = useState(() => {
    const fromUrl = parseSetParam(searchParams, 'agency');
    if (fromUrl.size > 0) return fromUrl;
    return agencyFilter ? new Set([agencyFilter]) : new Set();
  });
  const [selectedRegions, setSelectedRegions] = useState(() => parseSetParam(searchParams, 'region'));
  // URL param is named `category` (not `role`) to match the audit spec's
  // example (`?category=medical`) — it maps to the role_type field.
  const [selectedRoles, setSelectedRoles] = useState(() => parseSetParam(searchParams, 'category'));
  const [selectedTerms, setSelectedTerms] = useState(() => parseSetParam(searchParams, 'term'));
  const [selectedTraditions, setSelectedTraditions] = useState(() => parseSetParam(searchParams, 'tradition'));
  const [selectedReligions, setSelectedReligions] = useState(() => parseSetParam(searchParams, 'religion'));
  const [showFilters, setShowFilters] = useState(false);

  const [quizScores] = useState(loadQuizAgencyScores);
  const [sortMode, setSortMode] = useState(() => {
    const fromUrl = searchParams.get('sort');
    if (fromUrl === SORT_AGENCY || (fromUrl === SORT_RELEVANCE && quizScores)) return fromUrl;
    if (fromUrl === SORT_MIXED) return SORT_MIXED;
    return quizScores ? SORT_RELEVANCE : SORT_MIXED;
  });
  const [page, setPage] = useState(() => Math.max(1, parseInt(searchParams.get('page'), 10) || 1));

  function toggleFilter(setter, value) {
    setter(prev => {
      const next = new Set(prev);
      if (next.has(value)) next.delete(value);
      else next.add(value);
      return next;
    });
  }

  // Saved + inquiry
  const [savedIds, setSavedIds] = useState(() => {
    try {
      return new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
    } catch { return new Set(); }
  });
  const [showSavedOnly, setShowSavedOnly] = useState(false);
  const [inquiryOpp, setInquiryOpp] = useState(null);

  // Signed-out: favorites are device-owned, in localStorage (savedIds above).
  // Signed-in: Supabase's saved_opportunities table is the source of truth,
  // so favorites follow the user across devices. The two are merged (union,
  // never a wholesale overwrite) the moment a session first appears.
  const [session, setSession] = useState(null);

  // Loads the static fallback snapshot once on mount. Only applies it if
  // nothing has been set yet — if the live Supabase fetch below already won
  // the race, this must never clobber fresher data with the stale snapshot.
  useEffect(() => {
    let cancelled = false;
    fetch(FALLBACK_URL)
      .then((res) => {
        if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        setOpportunities((prev) => (prev === null ? data : prev));
      })
      .catch((err) => {
        if (cancelled) return;
        console.error('Failed to load the opportunities fallback snapshot:', err);
        setFallbackError(true);
      });
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    if (!supabase || !ENABLE_FRESH_FETCH) return;
    let cancelled = false;
    async function refresh() {
      setLoading(true);
      setLoadError(false);
      const allRows = [];
      const PAGE_SIZE = 1000;
      let from = 0;
      try {
        while (true) {
          const { data, error } = await supabase
            .from('opportunities')
            .select('id, agency, title, url, location, region, role_type, term_length, description')
            .eq('active', true)
            .order('agency', { ascending: true })
            .order('title', { ascending: true })
            .range(from, from + PAGE_SIZE - 1);
          if (cancelled) return;
          if (error) throw error;
          allRows.push(...(data || []));
          if (!data || data.length < PAGE_SIZE) break;
          from += PAGE_SIZE;
        }
        if (!cancelled && allRows.length > 0) {
          setOpportunities(allRows);
        }
      } catch (err) {
        if (cancelled) return;
        // Network hiccup or RLS misconfig — leave whatever the fallback
        // effect already loaded (or will load) in place rather than an
        // empty list, but surface it so a stale-data banner can render and
        // so this shows up in error monitoring instead of failing silently.
        console.error('Failed to load live opportunities, showing cached snapshot:', err);
        setLoadError(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    refresh();
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    localStorage.setItem('fielded_saved_opps', JSON.stringify([...savedIds]));
  }, [savedIds]);

  useEffect(() => {
    if (!supabase) return;
    supabase.auth.getSession().then(({ data }) => setSession(data.session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, newSession) => {
      setSession(newSession);
    });
    return () => listener.subscription.unsubscribe();
  }, []);

  // First sign-in: merge whatever was saved locally (signed-out browsing)
  // with whatever's already in Supabase for this user, so neither side gets
  // clobbered. Keyed on the user id, not the session object itself, since
  // onAuthStateChange also fires (with a new session object) on token
  // refresh — that must not re-run the merge on every refresh.
  const userId = session?.user?.id;
  useEffect(() => {
    if (!supabase || !userId) return;
    let cancelled = false;
    async function mergeFavorites() {
      const { data, error } = await supabase
        .from('saved_opportunities')
        .select('opportunity_id')
        .eq('user_id', userId);
      if (cancelled) return;
      if (error) {
        console.error('Failed to load saved opportunities from Supabase:', error);
        return;
      }
      const remoteIds = new Set((data || []).map((r) => r.opportunity_id));
      let localIds = new Set();
      try {
        localIds = new Set(JSON.parse(localStorage.getItem('fielded_saved_opps') || '[]'));
      } catch {
        // ignore malformed cache
      }
      const missingFromRemote = [...localIds].filter((id) => !remoteIds.has(id));
      if (missingFromRemote.length > 0) {
        const { error: upsertError } = await supabase
          .from('saved_opportunities')
          .upsert(missingFromRemote.map((id) => ({ user_id: userId, opportunity_id: id })), {
            onConflict: 'user_id,opportunity_id'
          });
        if (upsertError) console.error('Failed to merge local favorites into Supabase:', upsertError);
      }
      if (!cancelled) setSavedIds(new Set([...remoteIds, ...localIds]));
    }
    mergeFavorites();
    return () => { cancelled = true; };
  }, [userId]);

  const agencies = useMemo(
    () => [...new Set((opportunities || []).map((o) => o.agency))].sort(),
    [opportunities]
  );

  // Every filter dimension applied except `search`/`showSavedOnly` (which
  // apply everywhere) and whichever dimension `skipKey` names — that's what
  // makes a facet count reflect "how many results if I also picked this
  // option", not "how many results right now" (which would just repeat the
  // header count on every chip and zero out sibling options in the same
  // group the instant one is selected).
  function baseFilteredList(list, skipKey) {
    // Category pages ("Serve in Albania", "{Category} — Avant") aren't
    // individual openings — sanitize.js (P1-C) flags them via listing_type
    // so they're excluded from the default list rather than padding it with
    // entries that don't represent a real, distinct role.
    let out = list.filter((o) => o.listing_type !== 'category_page');
    if (showSavedOnly) out = out.filter((o) => savedIds.has(o.id));
    if (search) {
      const q = search.toLowerCase();
      out = out.filter((o) =>
        o.title.toLowerCase().includes(q) ||
        (o.description || '').toLowerCase().includes(q) ||
        o.agency.toLowerCase().includes(q) ||
        (o.location || '').toLowerCase().includes(q)
      );
    }
    if (skipKey !== 'agency' && selectedAgencies.size > 0) out = out.filter((o) => selectedAgencies.has(o.agency));
    if (skipKey !== 'region' && selectedRegions.size > 0) out = out.filter((o) => selectedRegions.has(o.region));
    if (skipKey !== 'role' && selectedRoles.size > 0) out = out.filter((o) => selectedRoles.has(o.role_type));
    if (skipKey !== 'term' && selectedTerms.size > 0) out = out.filter((o) => selectedTerms.has(o.term_length));
    if (skipKey !== 'tradition' && selectedTraditions.size > 0) {
      out = out.filter((o) => {
        const tradition = getTradition(o);
        return tradition && selectedTraditions.has(tradition);
      });
    }
    if (skipKey !== 'religion' && selectedReligions.size > 0) {
      out = out.filter((o) => {
        const religions = getReligions(o);
        return religions.some((r) => selectedReligions.has(r));
      });
    }
    return out;
  }

  function countBy(list, field) {
    const counts = new Map();
    for (const o of list) {
      const v = o[field];
      if (v == null) continue;
      counts.set(v, (counts.get(v) || 0) + 1);
    }
    return counts;
  }

  const agencyCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'agency'), 'agency'),
    [opportunities, search, selectedRegions, selectedRoles, selectedTerms, showSavedOnly, savedIds]
  );
  const regionCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'region'), 'region'),
    [opportunities, search, selectedAgencies, selectedRoles, selectedTerms, showSavedOnly, savedIds]
  );
  const roleCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'role'), 'role_type'),
    [opportunities, search, selectedAgencies, selectedRegions, selectedTerms, selectedTraditions, showSavedOnly, savedIds]
  );
  const termCounts = useMemo(
    () => countBy(baseFilteredList(opportunities || [], 'term'), 'term_length'),
    [opportunities, search, selectedAgencies, selectedRegions, selectedRoles, selectedTraditions, showSavedOnly, savedIds]
  );
  const traditionCounts = useMemo(
    () => {
      const filtered = baseFilteredList(opportunities || [], 'tradition');
      const counts = new Map();
      for (const o of filtered) {
        const tradition = getTradition(o);
        if (tradition == null) continue;
        counts.set(tradition, (counts.get(tradition) || 0) + 1);
      }
      return counts;
    },
    [opportunities, search, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, selectedReligions, showSavedOnly, savedIds]
  );
  const religionCounts = useMemo(
    () => {
      const filtered = baseFilteredList(opportunities || [], 'religion');
      const counts = new Map();
      for (const o of filtered) {
        const religions = getReligions(o);
        for (const religion of religions) {
          counts.set(religion, (counts.get(religion) || 0) + 1);
        }
      }
      return counts;
    },
    [opportunities, search, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, selectedTraditions, showSavedOnly, savedIds]
  );

  const filtered = useMemo(() => {
    let list = baseFilteredList(opportunities || [], null);

    if (sortMode === SORT_AGENCY) {
      list = [...list].sort((a, b) => a.agency.localeCompare(b.agency) || a.title.localeCompare(b.title));
    } else if (sortMode === SORT_RELEVANCE && quizScores) {
      list = [...list].sort((a, b) => (quizScores.get(b.agency) ?? -1) - (quizScores.get(a.agency) ?? -1));
    } else {
      // SORT_MIXED (default): round-robin interleave by agency — see
      // interleaveByAgency() above for why this replaces raw alphabetical.
      list = interleaveByAgency(list);
    }

    return list;
  }, [opportunities, search, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, selectedTraditions, selectedReligions, showSavedOnly, savedIds, sortMode, quizScores]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const pageItems = useMemo(
    () => filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE),
    [filtered, page]
  );

  // Reset to page 1 whenever the result set could have changed shape —
  // search, filters, or sort — but not on first mount, so a shared/reloaded
  // URL like ?page=3&agency=ABWE actually lands on page 3 instead of always
  // snapping back to page 1.
  const isFirstFilterRender = useRef(true);
  useEffect(() => {
    if (isFirstFilterRender.current) {
      isFirstFilterRender.current = false;
      return;
    }
    setPage(1);
  }, [search, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, selectedTraditions, selectedReligions, sortMode, showSavedOnly]);

  // Clamp if filters shrank the result set out from under the current page
  // (e.g. on page 5 of "ABWE", then also filter to a term length with none).
  // Skipped while opportunities is still null — otherwise totalPages is
  // briefly 1 (nothing loaded yet) and this would snap a URL-provided
  // ?page=3 back down to 1 before the real data ever arrives.
  useEffect(() => {
    if (opportunities === null) return;
    if (page > totalPages) setPage(totalPages);
  }, [opportunities, page, totalPages]);

  // URL is the single source of truth for "what am I looking at" — every
  // page/filter/sort change re-serializes here so results stay shareable and
  // reloadable. `replace: true` avoids piling one history entry per
  // keystroke in the search box; Prev/Next/page-number clicks still update
  // this same URL (browser back still works, just steps over the whole
  // filter state rather than one field at a time).
  useEffect(() => {
    const next = new URLSearchParams();
    if (search) next.set('q', search);
    if (selectedAgencies.size > 0) next.set('agency', [...selectedAgencies].join(','));
    if (selectedRegions.size > 0) next.set('region', [...selectedRegions].join(','));
    if (selectedRoles.size > 0) next.set('category', [...selectedRoles].join(','));
    if (selectedTerms.size > 0) next.set('term', [...selectedTerms].join(','));
    if (selectedTraditions.size > 0) next.set('tradition', [...selectedTraditions].join(','));
    if (selectedReligions.size > 0) next.set('religion', [...selectedReligions].join(','));
    if (showSavedOnly) next.set('saved', '1');
    if (sortMode !== SORT_MIXED) next.set('sort', sortMode);
    if (page > 1) next.set('page', String(page));
    setSearchParams(next, { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [search, selectedAgencies, selectedRegions, selectedRoles, selectedTerms, selectedTraditions, selectedReligions, showSavedOnly, sortMode, page]);

  function toggleSave(id) {
    const wasSaved = savedIds.has(id);
    setSavedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

    // Signed in: Supabase is the source of truth, so the edit goes there
    // (and follows the user across devices). Signed out: the localStorage
    // effect above is the only persistence, same as before this feature.
    if (supabase && userId) {
      const write = wasSaved
        ? supabase.from('saved_opportunities').delete().match({ user_id: userId, opportunity_id: id })
        : supabase.from('saved_opportunities').upsert(
            { user_id: userId, opportunity_id: id },
            { onConflict: 'user_id,opportunity_id' }
          );
      write.then(({ error }) => {
        if (error) console.error('Failed to sync saved opportunity to Supabase:', error);
      });
    }
  }

  function clearFilters() {
    setSearch('');
    setSelectedAgencies(new Set());
    setSelectedRegions(new Set());
    setSelectedRoles(new Set());
    setSelectedTerms(new Set());
    setSelectedTraditions(new Set());
    setSelectedReligions(new Set());
    setShowSavedOnly(false);
  }

  const activeFilterCount = selectedAgencies.size + selectedRegions.size + selectedRoles.size + selectedTerms.size + selectedTraditions.size + selectedReligions.size;
  const hasActiveFilters = search || activeFilterCount > 0 || showSavedOnly;

  return (
    <div className="opp-explorer">
      {/* Search + filter bar */}
      <div className="opp-toolbar">
        <div className="opp-search-wrap">
          <MagnifyingGlass size={18} className="opp-search-icon" />
          <input
            type="search"
            className="opp-search"
            placeholder="Search opportunities..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
        <button
          type="button"
          className={`opp-filter-toggle${showFilters ? ' opp-filter-toggle--open' : ''}`}
          onClick={() => setShowFilters(!showFilters)}
        >
          <Funnel size={16} weight="bold" />
          Filters
          {activeFilterCount > 0 && <span className="opp-filter-badge">{activeFilterCount}</span>}
          <CaretDown size={14} className={`opp-caret${showFilters ? ' opp-caret--open' : ''}`} />
        </button>
        <button
          type="button"
          className={`opp-icon-btn opp-saved-toggle${showSavedOnly ? ' opp-icon-btn--saved' : ''}`}
          onClick={() => setShowSavedOnly(!showSavedOnly)}
          aria-label={showSavedOnly ? 'Show all' : 'Show saved only'}
        >
          <Heart weight={showSavedOnly ? 'fill' : 'regular'} size={18} />
          <span className="opp-saved-count">{savedIds.size}</span>
        </button>
        <label className="opp-sort">
          <SortAscending size={16} weight="bold" />
          <span className="visually-hidden">Sort opportunities by</span>
          <select
            className="opp-sort-select"
            value={sortMode}
            onChange={(e) => setSortMode(e.target.value)}
          >
            {quizScores && <option value={SORT_RELEVANCE}>Relevance</option>}
            <option value={SORT_AGENCY}>Agency A–Z</option>
            <option value={SORT_MIXED}>All agencies (mixed)</option>
          </select>
        </label>
      </div>

      {sortMode === SORT_RELEVANCE && quizScores ? (
        <p className="opp-sort-pill">Sorted by your quiz matches</p>
      ) : !quizScores ? (
        <p className="opp-sort-hint">
          <Link to="/quiz">Start with a quick quiz</Link> to find your best fit — opportunities can then sort by relevance to your answers.
        </p>
      ) : null}

      {/* Expandable filter panel */}
      {showFilters && (
        <div className="opp-filters">
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Agency
              {selectedAgencies.size > 0 && <span className="opp-filter-label-count">{selectedAgencies.size}</span>}
            </span>
            <div className="opp-chip-row">
              {agencies.map((a) => (
                <FilterChip key={a} label={a} active={selectedAgencies.has(a)} count={agencyCounts.get(a) || 0}
                  onClick={() => toggleFilter(setSelectedAgencies, a)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Region
              {selectedRegions.size > 0 && <span className="opp-filter-label-count">{selectedRegions.size}</span>}
            </span>
            <div className="opp-chip-row">
              {REGIONS.map((r) => (
                <FilterChip key={r} label={r} active={selectedRegions.has(r)} count={regionCounts.get(r) || 0}
                  onClick={() => toggleFilter(setSelectedRegions, r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Role type
              {selectedRoles.size > 0 && <span className="opp-filter-label-count">{selectedRoles.size}</span>}
            </span>
            <div className="opp-chip-row">
              {ROLE_TYPES.map((r) => (
                <FilterChip key={r} label={r} active={selectedRoles.has(r)} count={roleCounts.get(r) || 0}
                  onClick={() => toggleFilter(setSelectedRoles, r)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Term length
              {selectedTerms.size > 0 && <span className="opp-filter-label-count">{selectedTerms.size}</span>}
            </span>
            <div className="opp-chip-row">
              {TERM_LENGTHS.map((t) => (
                <FilterChip key={t} label={t} active={selectedTerms.has(t)} count={termCounts.get(t) || 0}
                  onClick={() => toggleFilter(setSelectedTerms, t)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Agency tradition
              {selectedTraditions.size > 0 && <span className="opp-filter-label-count">{selectedTraditions.size}</span>}
            </span>
            <div className="opp-chip-row">
              {TRADITIONS.map((tradition) => (
                <FilterChip key={tradition} label={tradition} active={selectedTraditions.has(tradition)} count={traditionCounts.get(tradition) || 0}
                  onClick={() => toggleFilter(setSelectedTraditions, tradition)} />
              ))}
            </div>
          </div>
          <div className="opp-filter-group">
            <span className="opp-filter-label">
              Target religion
              {selectedReligions.size > 0 && <span className="opp-filter-label-count">{selectedReligions.size}</span>}
            </span>
            <div className="opp-chip-row">
              {RELIGIONS.map((religion) => (
                <FilterChip key={religion} label={religion} active={selectedReligions.has(religion)} count={religionCounts.get(religion) || 0}
                  onClick={() => toggleFilter(setSelectedReligions, religion)} />
              ))}
            </div>
          </div>
          {hasActiveFilters && (
            <button type="button" className="opp-clear-filters" onClick={clearFilters}>
              Clear all filters {activeFilterCount > 0 && `(${activeFilterCount})`}
            </button>
          )}
        </div>
      )}

      {/* Results */}
      {opportunities === null ? (
        fallbackError ? (
          <div className="opp-error" role="alert">
            <p>Couldn't load opportunities right now — try refreshing the page.</p>
          </div>
        ) : (
          <div className="opp-loading" role="status">
            <p className="visually-hidden">Loading opportunities…</p>
            {/* Matches PAGE_SIZE, not an arbitrary smaller count — a real
                page of results is 24 cards, and skeleton/real height
                parity is what keeps the footer from jumping down once
                the swap happens (measured via Lighthouse CLS). */}
            <div className="opp-grid" aria-hidden="true">
              {Array.from({ length: PAGE_SIZE }).map((_, i) => (
                <div className="opp-card-skeleton" key={i} />
              ))}
            </div>
          </div>
        )
      ) : (
        <>
          {loadError && (
            <p className="opp-error opp-error--inline" role="status">
              Couldn't reach live listings right now — showing a recent saved snapshot instead.
            </p>
          )}
          <div className="opp-results-header">
            <p className="opp-results-count">
              {filtered.length.toLocaleString()} {filtered.length === 1 ? 'opportunity' : 'opportunities'}
              {hasActiveFilters ? ' matching your filters' : ''}
              {loading ? ' (refreshing…)' : ''}
            </p>
          </div>

          {filtered.length === 0 ? (
            <div className="opp-empty">
              <p>No opportunities match your current filters.</p>
              {hasActiveFilters && (
                <button type="button" className="cta-button" onClick={clearFilters}>
                  Clear filters
                </button>
              )}
            </div>
          ) : (
            <>
              <div className="opp-grid">
                {pageItems.map((opp) => (
                  <OpportunityCard
                    key={opp.id}
                    opp={opp}
                    saved={savedIds.has(opp.id)}
                    onToggleSave={toggleSave}
                    onInquire={setInquiryOpp}
                  />
                ))}
              </div>

              {totalPages > 1 && (
                <nav className="opp-pagination" aria-label="Opportunities pages">
                  <button
                    type="button"
                    className="opp-page-btn"
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                    disabled={page <= 1}
                  >
                    <CaretLeft size={16} weight="bold" /> Previous
                  </button>
                  <span className="opp-page-status">
                    Page {page} of {totalPages}
                  </span>
                  <button
                    type="button"
                    className="opp-page-btn"
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                    disabled={page >= totalPages}
                  >
                    Next <CaretRight size={16} weight="bold" />
                  </button>
                </nav>
              )}
            </>
          )}
        </>
      )}

      <InquiryModal opportunity={inquiryOpp} onClose={() => setInquiryOpp(null)} />
    </div>
  );
}
