#!/usr/bin/env node

// Generates public/sitemap.xml from a single explicit route list, run as
// part of `npm run build:prerender` (before `vite build`, so the copy
// under public/ that Vite copies into dist/ is always current).
//
// This list is intentionally its own thing, not a filtered copy of
// scripts/prerender.js's ROUTES: that list is "what gets prerendered HTML"
// (every route, including gated/admin ones, since a direct hit still needs
// a real <title>), while this one is "what search engines should crawl and
// index" — a much smaller, curated set. Every route left out here already
// opts out for a real reason: it's behind auth (missionary-support
// dashboard, onboarding forms, the admin review queue), or it's a
// per-record dynamic page (for-churches/:missionaryId) that also sets
// `noindex: true` via usePageMeta (see src/pages/MissionaryProfilePage.jsx)
// — so leaving it out of the sitemap and marking it noindex agree with each
// other instead of contradicting.
import { writeFileSync } from 'fs';

const BASE_URL = process.env.VITE_SITE_URL || 'https://missions-hub.vercel.app';

const ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/map', changefreq: 'weekly', priority: '0.9' },
  { path: '/quiz', changefreq: 'monthly', priority: '0.8' },
  { path: '/opportunities', changefreq: 'weekly', priority: '0.8' },
  { path: '/checklist', changefreq: 'monthly', priority: '0.7' },
  { path: '/prayer-map', changefreq: 'weekly', priority: '0.6' },
  { path: '/for-churches', changefreq: 'weekly', priority: '0.6' },
  { path: '/about', changefreq: 'monthly', priority: '0.5' },
  { path: '/terms', changefreq: 'yearly', priority: '0.2' },
  { path: '/privacy', changefreq: 'yearly', priority: '0.2' }
];

const today = new Date().toISOString().slice(0, 10);

const body = ROUTES.map(
  ({ path, changefreq, priority }) => `  <url>
    <loc>${BASE_URL}${path}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`
).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.js — do not edit by hand.
     Route list lives in that script; re-run "npm run generate-sitemap"
     (or "npm run build:prerender", which calls it automatically) after
     adding/removing a public route. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

writeFileSync('public/sitemap.xml', xml);
console.log(`Wrote public/sitemap.xml with ${ROUTES.length} routes.`);
